"""
Schema Pack Registry — domain-specific schema bundles.

A pack is a named YAML manifest that lists node types and spaces
for a specific domain (e.g. biomedical, legal, saas).

Installing a pack creates YAML type schemas in schemas/types/ so they
are picked up by the loader and validated by the grammar validator.

Pack lifecycle:
  list_packs()           — show available packs
  get_pack(name)         — load pack manifest
  install_pack(name)     — generate type schemas from pack manifest
  uninstall_pack(name)   — remove generated type schemas (with safety check)
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_PACKS_DIR = Path(__file__).parent / "packs"
_TYPES_DIR = Path(__file__).parent / "types"

# Header comment prepended to every generated type schema.
_TYPE_TEMPLATE_HEADER = """\
# Auto-generated by schema pack '{pack_name}' v{pack_version}
# Remove this file or run pack uninstall to revert.
"""


def _build_type_schema(pack: dict[str, Any], node_type: str) -> dict[str, Any]:
    """Build a validator-compatible schema dict for *node_type* from *pack*.

    Uses ``type_specs`` in the pack manifest (per-type space/required/optional)
    when present, falling back to the pack's default space and a generic
    name/description/status shape otherwise. Output mirrors the hand-written
    schemas in schemas/types/ (type/version/space/properties) so
    grammar.validator.validate_node_properties actually enforces it.
    """
    type_specs = pack.get("type_specs", {}) or {}
    spec = type_specs.get(node_type, {}) or {}
    default_space = (pack.get("spaces") or ["concept"])[0]
    space = spec.get("space", default_space)
    required_fields = spec.get("required") or ["name"]
    optional_fields = spec.get("optional") or ["description", "status"]

    properties: dict[str, Any] = {}
    for field_name in required_fields:
        properties[field_name] = {"type": "string", "required": True, "nullable": False}
    for field_name in optional_fields:
        properties[field_name] = {"type": "string", "required": False, "nullable": True}

    return {
        "type": node_type,
        "version": pack.get("version", "1.0.0"),
        "space": space,
        "pack": pack["name"],
        "properties": properties,
    }


def _is_legacy_shape(data: Any) -> bool:
    """Return True if *data* is a dict with legacy required/optional and no properties.

    Older versions of ``_build_type_schema`` wrote ``node_type/pack/required/
    optional`` with no ``properties`` mapping. ``validate_node_properties``
    only reads ``schema.get("properties", {})``, so those stubs validate as
    a permanent no-op. Guards against non-dict YAML (a bare list/scalar is
    valid YAML but has no ``.get``) by just saying "not legacy shape".
    """
    return (
        isinstance(data, dict)
        and "properties" not in data
        and ("required" in data or "optional" in data)
    )


def _has_generation_marker(content: str, pack_name: str) -> bool:
    """Return True if *content* carries this tool's own generated-file header.

    This -- not the ``pack:`` YAML field -- is what makes a file safe to
    overwrite. A user could hand-write ``pack: biomedical`` into their own
    customised file (e.g. copy-pasted from a real stub), so the field alone
    is not proof install_pack produced it. The literal header comment from
    ``_TYPE_TEMPLATE_HEADER`` is under this tool's exclusive control.
    """
    return content.startswith(f"# Auto-generated by schema pack '{pack_name}'")


def list_packs() -> list[dict[str, Any]]:
    """Return metadata for all available schema packs."""
    packs = []
    for path in sorted(_PACKS_DIR.glob("*.yaml")):
        try:
            import yaml  # type: ignore[import]
            with open(path, encoding="utf-8") as f:
                data = yaml.safe_load(f)
            if data and "name" in data:
                packs.append({
                    "name": data["name"],
                    "version": data.get("version", "unknown"),
                    "description": (data.get("description") or "").strip(),
                    "types": data.get("types", []),
                    "spaces": data.get("spaces", []),
                    "installed": _is_pack_installed(data["name"], data.get("types", [])),
                })
        except Exception as exc:
            logger.warning("Failed to load pack %s: %s", path.name, exc)
    return packs


def get_pack(name: str) -> dict[str, Any] | None:
    """Load a specific pack manifest by name."""
    path = _PACKS_DIR / f"{name}.yaml"
    if not path.exists():
        return None
    try:
        import yaml
        with open(path, encoding="utf-8") as f:
            return yaml.safe_load(f)
    except Exception as exc:
        logger.error("Failed to load pack '%s': %s", name, exc)
        return None


def install_pack(name: str) -> dict[str, Any]:
    """
    Install a schema pack by generating type YAML files.

    Each type in the pack gets a stub schema written to schemas/types/.
    Existing schemas are NOT overwritten -- unless they are a legacy-shape
    stub (required/optional, no properties) that also carries this tool's
    own generation header (see ``_is_legacy_shape`` / ``_has_generation_marker``),
    in which case they are regenerated in place ("migrated") since the old
    shape made validation a permanent no-op. A legacy-shape file WITHOUT
    that header is left untouched and only warned about, since it could be
    hand-written (the ``pack:`` field alone is not proof install_pack wrote
    it -- a user can type that too). Migrating drops any old required/
    optional values that the pack manifest doesn't also define; that loss
    is reported in ``discarded_constraints`` and logged.

    Returns a result dict with created/migrated/skipped counts.
    """
    pack = get_pack(name)
    if not pack:
        return {"error": f"Pack '{name}' not found. Available: {[p['name'] for p in list_packs()]}"}

    import yaml

    _TYPES_DIR.mkdir(parents=True, exist_ok=True)

    created = []
    migrated = []
    skipped = []
    discarded_constraints: dict[str, dict[str, list[str]]] = {}

    for node_type in pack.get("types", []):
        path = _TYPES_DIR / f"{node_type}.yaml"
        header = _TYPE_TEMPLATE_HEADER.format(
            pack_name=pack["name"],
            pack_version=pack.get("version", "1.0.0"),
        )
        if path.exists():
            existing_content = path.read_text(encoding="utf-8")
            try:
                existing = yaml.safe_load(existing_content)
            except Exception as exc:
                logger.warning("Pack '%s': failed to read existing schema for %s: %s", name, node_type, exc)
                skipped.append(node_type)
                continue
            if not _is_legacy_shape(existing):
                skipped.append(node_type)
                continue
            if not _has_generation_marker(existing_content, name):
                logger.warning(
                    "Pack '%s': %s has a legacy shape (required/optional, no "
                    "properties) but lacks this tool's generation header, so "
                    "it will NOT be auto-migrated -- it may be hand-written. "
                    "Inspect it manually and add `properties` yourself.",
                    name, node_type,
                )
                skipped.append(node_type)
                continue
            old_required = existing.get("required") or []
            old_optional = existing.get("optional") or []
            schema = _build_type_schema(pack, node_type)
            content = header + yaml.safe_dump(schema, sort_keys=False, allow_unicode=True)
            path.write_text(content, encoding="utf-8")
            migrated.append(node_type)
            if old_required or old_optional:
                discarded_constraints[node_type] = {"required": old_required, "optional": old_optional}
                logger.warning(
                    "Pack '%s': migrated %s, discarding legacy required=%r optional=%r "
                    "(field list is now defined by the pack manifest's type_specs instead)",
                    name, node_type, old_required, old_optional,
                )
            else:
                logger.info("Pack '%s': migrated legacy-shape schema for %s", name, node_type)
            continue
        schema = _build_type_schema(pack, node_type)
        content = header + yaml.safe_dump(schema, sort_keys=False, allow_unicode=True)
        path.write_text(content, encoding="utf-8")
        created.append(node_type)
        logger.info("Pack '%s': created schema for %s", name, node_type)

    # Invalidate loader cache
    try:
        from opencrab.schemas.loader import reload_schema
        for t in created + migrated:
            reload_schema(t)
    except Exception as exc:
        logger.warning("Pack '%s': failed to reload schema cache: %s", name, exc)

    return {
        "pack": name,
        "version": pack.get("version"),
        "created": created,
        "migrated": migrated,
        "skipped": skipped,
        "discarded_constraints": discarded_constraints,
        "total_types": len(pack.get("types", [])),
    }


def uninstall_pack(name: str, force: bool = False) -> dict[str, Any]:
    """
    Remove type schemas generated by a pack.

    Only removes schemas that have `pack: <name>` in their YAML header
    (i.e. were auto-generated). User-customised schemas are kept unless
    force=True.
    """
    pack = get_pack(name)
    if not pack:
        return {"error": f"Pack '{name}' not found."}

    removed = []
    kept = []

    for node_type in pack.get("types", []):
        path = _TYPES_DIR / f"{node_type}.yaml"
        if not path.exists():
            continue
        try:
            content = path.read_text(encoding="utf-8")
            is_generated = f"pack: {name}" in content
            if is_generated or force:
                path.unlink()
                removed.append(node_type)
            else:
                kept.append(node_type)
        except Exception as exc:
            logger.warning("Failed to remove schema %s: %s", node_type, exc)
            kept.append(node_type)

    return {
        "pack": name,
        "removed": removed,
        "kept_user_customised": kept,
    }


def _is_pack_installed(name: str, types: list[str]) -> bool:
    """Return True if at least one type from the pack has a schema file."""
    return any((_TYPES_DIR / f"{t}.yaml").exists() for t in types)
