"""
Schema Pack Registry — domain-specific schema bundles.

A pack is a named YAML manifest that lists node types and spaces
for a specific domain (e.g. biomedical, legal, saas).

Installing a pack creates YAML type schemas in schemas/types/ so they
are picked up by the loader and validated by the grammar validator.

Pack lifecycle:
  list_packs()           — show available packs
  get_pack(name)         — load pack manifest
  install_pack(name)     — generate type schemas from pack manifest
  uninstall_pack(name)   — remove generated type schemas (with safety check)

Naming contract (#109). A pack name, and every type name in a manifest,
must be a single path component -- no path separators (either flavour),
not "." or "..", not absolute, no NUL. Names are joined onto a directory
to form a file path, and ``pathlib``'s ``/`` neither resolves ``..`` nor
rejects an absolute right-hand operand, so an unchecked name addresses a
file outside the directory it was supposed to name. An unsafe pack name
reads as "pack not found"; a manifest carrying an unsafe type name is
refused whole, before anything is created or deleted. A name is unsafe if
it carries a separator (either flavour), is "." or "..", is absolute, or
is reserved as a filename by Windows -- a reserved character or a DOS device
name such as CON. A trailing dot or space is refused too, which is stricter
than the resulting ``.yaml`` filename needs; ``safe_schema_name`` documents
why that one is deliberate.

Symlink policy (#109), which is NOT the same in both directions:

- Reading a pack manifest from the pack directory FOLLOWS symlinks. This
  matches ``list_packs``, which globs that directory and follows links, so
  a symlinked pack is listed and installable rather than listed and then
  "not found". Planting such a link needs write access to that directory,
  which is outside this module's threat model -- what it defends against is
  an unsafe NAME, not an already-modified directory.
- Writing and deleting a type schema refuses a path that resolves outside
  the type directory (``loader.resolves_inside``). A link that resolves to
  another direct child inside it still passes, and the write then follows
  it like any other file operation; ``unlink`` removes the link itself,
  though the generated-header read just before it follows the link. The
  delete path never reaches the check for a dangling link, because
  ``exists()`` is false and the type is skipped first.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from opencrab.schemas.loader import resolves_inside, safe_schema_name

logger = logging.getLogger(__name__)

_PACKS_DIR = Path(__file__).parent / "packs"
_TYPES_DIR = Path(__file__).parent / "types"

# Header comment prepended to every generated type schema.
_TYPE_TEMPLATE_HEADER = """\
# Auto-generated by schema pack '{pack_name}' v{pack_version}
# Remove this file or run pack uninstall to revert.
"""


def _build_type_schema(
    pack: dict[str, Any],
    node_type: str,
    extra_required: list[str] | None = None,
    extra_optional: list[str] | None = None,
) -> dict[str, Any]:
    """Build a validator-compatible schema dict for *node_type* from *pack*.

    Uses ``type_specs`` in the pack manifest (per-type space/required/optional)
    when present, falling back to the pack's default space and a generic
    name/description/status shape otherwise. Output mirrors the hand-written
    schemas in schemas/types/ (type/version/space/properties) so
    grammar.validator.validate_node_properties actually enforces it.

    *extra_required*/*extra_optional* let a legacy-stub migration carry over
    field names the manifest doesn't define -- e.g. a field a user added by
    hand to a previously-installed stub. Required wins if a name appears in
    both.

    Legacy shape only ever stored flat field-name lists -- no per-field type,
    so these extra fields get NO ``type``: inventing "string" would be a
    guess, and grammar.validator.validate_node_properties now actually
    enforces declared types (#48), so a wrong guess would reject real data
    (e.g. a numeric field the user marked required). Omitting ``type``
    entirely, rather than declaring an unknown-to-the-validator type name,
    is deliberate: the validator's type-check loop only runs when
    ``spec.get("type")`` is not None, so an absent key skips the check
    silently (no per-node warning-log spam), while presence + required-ness
    are still enforced.

    No property here ever gets a ``nullable`` key, manifest-defined or
    extra. grammar.validator.validate_node_properties derives an absent
    ``nullable`` from ``required`` (required -> non-nullable, optional ->
    nullable; see ``_is_nullable`` there, #49/#106), which is exactly the
    meaning these generated schemas intend, so writing the key would only
    duplicate ``required``. That duplication is exactly what regressed when a
    manifest-optional field got promoted to required by *extra_required*
    below: the promotion flipped ``required`` but not the already-written
    ``nullable``, producing a self-contradictory required-and-nullable
    schema. One key can't disagree with itself. A hand-written schema that
    needs the other pairing declares ``nullable`` explicitly and wins.
    """
    type_specs = pack.get("type_specs", {}) or {}
    spec = type_specs.get(node_type, {}) or {}
    default_space = (pack.get("spaces") or ["concept"])[0]
    space = spec.get("space", default_space)
    required_fields = list(spec.get("required") or ["name"])
    optional_fields = list(spec.get("optional") or ["description", "status"])

    # #107: a manifest can (by author mistake) list the same field in both
    # `required` and `optional`. Surface it -- required still wins below,
    # but a pack author should know their manifest contradicts itself.
    overlap = sorted(set(required_fields) & set(optional_fields))
    if overlap:
        logger.warning(
            "Pack '%s': type '%s' manifest lists %r in both required and "
            "optional -- required wins.",
            pack.get("name"), node_type, overlap,
        )

    properties: dict[str, Any] = {}
    for field_name in required_fields:
        properties[field_name] = {"type": "string", "required": True}
    for field_name in optional_fields:
        # #107: without this guard, a field declared in both `required` and
        # `optional` had its required-ness silently dropped -- this loop
        # unconditionally overwrote whatever the required-fields loop above
        # just wrote. The extra_required/extra_optional handling below
        # already guards the same way; the manifest's own lists didn't.
        if field_name not in properties:
            properties[field_name] = {"type": "string", "required": False}

    for field_name in extra_required or []:
        if field_name in properties:
            properties[field_name]["required"] = True
        else:
            properties[field_name] = {"required": True}
    for field_name in extra_optional or []:
        if field_name not in properties:
            properties[field_name] = {"required": False}

    return {
        "type": node_type,
        "version": pack.get("version", "1.0.0"),
        "space": space,
        "pack": pack["name"],
        "properties": properties,
    }


def _is_legacy_shape(data: Any) -> bool:
    """Return True if *data* is a dict with legacy required/optional and no properties.

    Older versions of ``_build_type_schema`` wrote ``node_type/pack/required/
    optional`` with no ``properties`` mapping. ``validate_node_properties``
    only reads ``schema.get("properties", {})``, so those stubs validate as
    a permanent no-op. Guards against non-dict YAML (a bare list/scalar is
    valid YAML but has no ``.get``) by just saying "not legacy shape".
    """
    return (
        isinstance(data, dict)
        and "properties" not in data
        and ("required" in data or "optional" in data)
    )


def _has_generation_marker(content: str, pack_name: str) -> bool:
    """Return True if *content* carries this tool's own generated-file header.

    This -- not the ``pack:`` YAML field -- is what makes a file safe to
    overwrite. A user could hand-write ``pack: biomedical`` into their own
    customised file (e.g. copy-pasted from a real stub), so the field alone
    is not proof install_pack produced it. The literal header comment from
    ``_TYPE_TEMPLATE_HEADER`` is under this tool's exclusive control.
    """
    return content.startswith(f"# Auto-generated by schema pack '{pack_name}'")


def _unsafe_names(names: list[Any]) -> list[Any]:
    """Return the entries of *names* that are not safe path components (#109).

    Used to vet a whole manifest BEFORE anything is created or deleted: a
    manifest carrying an escaping type name is a broken manifest, and a
    partial install/uninstall would leave exactly the mess this check exists
    to prevent. See ``opencrab.schemas.loader.safe_schema_name``.
    """
    return [n for n in names if not safe_schema_name(n)]


def _unsafe_names_error(pack_name: str, rejected: list[Any]) -> dict[str, str]:
    """Build the refusal returned by install_pack/uninstall_pack."""
    return {
        "error": (
            f"Pack '{pack_name}' manifest has unsafe type name(s): {rejected!r}. "
            "A type name must be a single path component: no path separators, "
            "not '.' or '..', not absolute, and not reserved as a filename by "
            "Windows (no control or reserved characters, no DOS device name "
            "such as CON, no trailing dot or space)."
        )
    }


def list_packs() -> list[dict[str, Any]]:
    """Return metadata for all available schema packs."""
    packs = []
    for path in sorted(_PACKS_DIR.glob("*.yaml")):
        try:
            import yaml  # type: ignore[import]
            with open(path, encoding="utf-8") as f:
                data = yaml.safe_load(f)
            if data and "name" in data:
                # #109: never advertise a name that get_pack will refuse. The
                # listing is what a client picks from and feeds back in, so
                # offering a refused name produces "Pack 'X' not found.
                # Available: ['X']" and an option that can never be taken.
                # The DECLARED name is checked, not the filename, because the
                # declared name is the value that goes back out to the client.
                if not safe_schema_name(data["name"]):
                    logger.warning(
                        "Skipping pack manifest %s: its declared name %r is not a "
                        "safe path component, so it could never be installed.",
                        path.name, data["name"],
                    )
                    continue
                # #109: the declared name being safe is not enough. install
                # vets the WHOLE type list and refuses the manifest outright if
                # any entry is unsafe, so advertising it would offer a pack that
                # can never be taken. Deliberately the same _unsafe_names the
                # install preflight calls, so both judge a name by one rule.
                rejected_types = _unsafe_names(data.get("types", []) or [])
                if rejected_types:
                    logger.warning(
                        "Skipping pack manifest %s: unsafe type name(s) %r, so "
                        "install would refuse the whole manifest.",
                        path.name, rejected_types,
                    )
                    continue
                packs.append({
                    "name": data["name"],
                    "version": data.get("version", "unknown"),
                    "description": (data.get("description") or "").strip(),
                    "types": data.get("types", []),
                    "spaces": data.get("spaces", []),
                    "installed": _is_pack_installed(data["name"], data.get("types", [])),
                })
        except Exception as exc:
            logger.warning("Failed to load pack %s: %s", path.name, exc)
    return packs


def get_pack(name: str) -> dict[str, Any] | None:
    """Load a specific pack manifest by name."""
    if not safe_schema_name(name):
        logger.warning(
            "Refusing to load pack %r: the pack name is not a safe path "
            "component (no separators, not '.'/'..', not absolute, not "
            "reserved as a filename by Windows).",
            name,
        )
        return None
    path = _PACKS_DIR / f"{name}.yaml"
    if not path.exists():
        return None
    try:
        import yaml
        with open(path, encoding="utf-8") as f:
            return yaml.safe_load(f)
    except Exception as exc:
        logger.error("Failed to load pack '%s': %s", name, exc)
        return None


def install_pack(name: str) -> dict[str, Any]:
    """
    Install a schema pack by generating type YAML files.

    Each type in the pack gets a stub schema written to schemas/types/.
    Existing schemas are NOT overwritten -- unless they are a legacy-shape
    stub (required/optional, no properties) that also carries this tool's
    own generation header (see ``_is_legacy_shape`` / ``_has_generation_marker``),
    in which case they are regenerated in place ("migrated") since the old
    shape made validation a permanent no-op. A legacy-shape file WITHOUT
    that header is left untouched and only warned about, since it could be
    hand-written (the ``pack:`` field alone is not proof install_pack wrote
    it -- a user can type that too). A generation-header stub can also have
    been hand-edited *after* install (a natural way to add a constraint) --
    migrating never drops a required/optional field the old file had, even
    if the pack manifest doesn't define it: any such extra field is carried
    over into the new ``properties`` and reported in
    ``preserved_extra_fields``, decided before anything is written to disk.

    The reverse edit -- a user removing a manifest-required field from the
    stub's ``required``/``optional`` lists -- is NOT honoured: a file that no
    longer declares the pack's own required fields isn't this pack's schema
    to keep incomplete, and re-deciding that is not migration's call. The
    manifest's fields are always regenerated. But that revival is not silent:
    any manifest-required field the old file no longer required (dropped
    entirely or demoted to ``optional``) is reported in
    ``revived_manifest_fields``, again decided before the write.

    A CURRENT-shape file (already has ``properties``) carrying this tool's
    generation header is also inspected, not skipped outright (#107, PR #336
    review): if a field the CURRENT manifest lists in *both* ``required``
    and ``optional`` is on disk as ``required: false`` -- exactly what a
    schema generated before the #107 fix looks like -- that field alone is
    flipped back to ``true`` and reported in ``revived_manifest_fields``,
    same as a migrated legacy stub. The repair is deliberately limited to
    that required/optional-overlap fingerprint: a manifest-required field
    that was never also optional could not have been produced by the
    overlap bug, so leaving it ``required: false`` is instead a deliberate
    operator edit, not a stale bug, and is not touched. Anything else about
    the file (other fields, their values) is left untouched too. A
    current-shape file without the header, with a non-mapping body or
    ``properties``, or with no such stale field, is left alone and counted
    as ``skipped``, same as before.

    Known limitation (#107, PR #336 review, round 3): the fingerprint is the
    CURRENT manifest's required/optional overlap, not the overlap that held
    when the on-disk file was generated. If a later pack version fixes its
    own manifest by dropping the field from ``optional`` (so the overlap no
    longer exists), a stale ``required: false`` left over from the old,
    still-overlapping manifest is no longer recognized and stays unrepaired.
    Closing that gap needs a per-file record of which manifest version (or
    fingerprint) generated it, which no migration path in this function
    tracks today (the legacy ``extra_required``/``extra_optional`` path has
    the same current-manifest-only limitation). Left as a follow-up rather
    than added here.

    Returns a result dict with created/migrated/skipped counts.
    """
    pack = get_pack(name)
    if not pack:
        return {"error": f"Pack '{name}' not found. Available: {[p['name'] for p in list_packs()]}"}

    import yaml

    # #109: vet EVERY type name before touching the filesystem -- ahead of the
    # mkdir, so "nothing was written" is literally true on refusal.
    rejected = _unsafe_names(pack.get("types", []) or [])
    if rejected:
        logger.warning("Pack '%s': refusing to install, unsafe type name(s) %r", name, rejected)
        return _unsafe_names_error(name, rejected)

    _TYPES_DIR.mkdir(parents=True, exist_ok=True)

    created = []
    migrated = []
    skipped = []
    preserved_extra_fields: dict[str, dict[str, list[str]]] = {}
    revived_manifest_fields: dict[str, dict[str, list[str]]] = {}

    for node_type in pack.get("types", []):
        path = _TYPES_DIR / f"{node_type}.yaml"
        # #109 residual guard: the name is safe, but the entry itself can be a
        # symlink pointing out of the directory. A DANGLING outward link reads
        # as exists()==False, so without this the branch below would treat it
        # as new and write_text would follow it and create the file outside.
        if not resolves_inside(path, _TYPES_DIR):
            logger.warning(
                "Pack '%s': %s resolves outside the type directory; not writing it.",
                name, node_type,
            )
            skipped.append(node_type)
            continue
        header = _TYPE_TEMPLATE_HEADER.format(
            pack_name=pack["name"],
            pack_version=pack.get("version", "1.0.0"),
        )
        if path.exists():
            try:
                existing_content = path.read_text(encoding="utf-8")
                existing = yaml.safe_load(existing_content)
            except Exception as exc:
                logger.warning("Pack '%s': failed to read existing schema for %s: %s", name, node_type, exc)
                skipped.append(node_type)
                continue
            if not _is_legacy_shape(existing):
                if not isinstance(existing, dict) or not _has_generation_marker(existing_content, name):
                    # Same safety bar as the legacy-shape path below: don't
                    # touch a file we can't prove we generated. A generation
                    # header on non-mapping YAML (hand-edited or corrupted
                    # after install) fails `_is_legacy_shape` too (#107
                    # review round 2: it must not crash trying to `.get()`
                    # off a list/scalar), so it lands here as an ordinary
                    # skip rather than an AttributeError.
                    skipped.append(node_type)
                    continue
                existing_properties = existing.get("properties")
                if not isinstance(existing_properties, dict):
                    skipped.append(node_type)
                    continue
                # #107 (PR #336 review rounds 5 and 6): a YAML anchor can
                # alias `properties` itself onto another key (e.g.
                # `saved_properties: &props {...}`, `properties: *props`),
                # or alias one property spec onto another (`name: &spec
                # {...}`, `description: *spec`) -- either way,
                # yaml.safe_load hands back the SAME dict object for both
                # sides of the alias. Mutating any of it in place, at any
                # depth, would leak the repair into whatever else shares
                # that object. A single `copy.deepcopy` is NOT enough here:
                # deepcopy's memo preserves internal aliasing on purpose
                # (two keys that pointed at the same object before the copy
                # still point at the same, newly-copied object after it),
                # so it detaches this dict from anything OUTSIDE it (round
                # 6's `saved_properties`/`properties` sharing) but does
                # nothing for sharing BETWEEN its own values (round 5's
                # `name`/`description` sharing). Give every dict-valued
                # entry its own fresh shallow copy instead -- this detaches
                # the container from outside sharing (round 6) and gives
                # each property spec its own object regardless of any
                # aliasing it had before the copy (round 5), in one pass.
                existing_properties = {
                    key: (dict(value) if isinstance(value, dict) else value)
                    for key, value in existing_properties.items()
                }
                manifest_spec = (pack.get("type_specs", {}) or {}).get(node_type, {}) or {}
                manifest_required = manifest_spec.get("required") or ["name"]
                manifest_optional = manifest_spec.get("optional") or ["description", "status"]
                # #107 (PR #336 review round 2): only a field the CURRENT
                # manifest lists in both `required` and `optional` can be
                # the overlap bug's stale output -- a manifest-required
                # field that was never also optional could not have been
                # written `required: false` by that bug, so restoring it
                # would instead reverse a deliberate operator edit
                # (current-shape files were never touched before this
                # branch existed). Repair is limited to that fingerprint.
                overlap = set(manifest_required) & set(manifest_optional)
                # #107 (PR #336 review): a schema generated before this fix
                # can already have such an overlapping field written to disk
                # as `required: false` -- exactly the bug this issue closes.
                # Without this branch, a bare reinstall never reaches the
                # fixed _build_type_schema for an already current-shape
                # file, so that stale False would persist forever. Only a
                # field that is provably this tool's own dict-shaped
                # property gets flipped -- anything else (a field missing
                # entirely, or one the user customised) is left alone, same
                # as extra_required/extra_optional below.
                stale_required = [
                    f
                    for f in manifest_required
                    if f in overlap
                    and isinstance(existing_properties.get(f), dict)
                    and existing_properties[f].get("required") is False
                ]
                if not stale_required:
                    skipped.append(node_type)
                    continue
                for f in stale_required:
                    # Each entry in existing_properties already got its own
                    # fresh copy above, so this write can't leak into any
                    # structure the original file's YAML anchors shared it
                    # with.
                    existing_properties[f]["required"] = True
                schema = dict(existing)
                schema["properties"] = existing_properties
                # #107 (PR #336 review round 4): this is a surgical, one-field
                # repair, not a regeneration -- `schema` keeps every other key
                # from `existing` untouched, including its own `version`. The
                # header comment must say the same version, not the current
                # pack's, or the file ends up claiming (in its header) to be
                # fully generated by a newer pack version while every field
                # except the repaired one still comes from the old one.
                repair_header = _TYPE_TEMPLATE_HEADER.format(
                    pack_name=pack["name"],
                    pack_version=existing.get("version", pack.get("version", "1.0.0")),
                )
                content = repair_header + yaml.safe_dump(schema, sort_keys=False, allow_unicode=True)
                path.write_text(content, encoding="utf-8")
                migrated.append(node_type)
                revived_manifest_fields[node_type] = {"required": stale_required, "optional": []}
                logger.warning(
                    "Pack '%s': repaired stale required=False on manifest-required "
                    "field(s) %r for %s (schema generated before the #107 fix)",
                    name, stale_required, node_type,
                )
                continue
            if not _has_generation_marker(existing_content, name):
                logger.warning(
                    "Pack '%s': %s has a legacy shape (required/optional, no "
                    "properties) but lacks this tool's generation header, so "
                    "it will NOT be auto-migrated -- it may be hand-written. "
                    "Inspect it manually and add `properties` yourself.",
                    name, node_type,
                )
                skipped.append(node_type)
                continue

            # Decide what would change BEFORE writing anything.
            old_required = existing.get("required") or []
            old_optional = existing.get("optional") or []
            manifest_spec = (pack.get("type_specs", {}) or {}).get(node_type, {}) or {}
            manifest_required = manifest_spec.get("required") or ["name"]
            manifest_optional = manifest_spec.get("optional") or ["description", "status"]

            # Fields the user added that the manifest doesn't define -- kept.
            extra_required = [f for f in old_required if f not in manifest_required]
            extra_optional = [
                f
                for f in old_optional
                if f not in manifest_optional and f not in manifest_required and f not in extra_required
            ]
            # Manifest-required fields the old file no longer required --
            # dropped from `required` entirely, or just demoted to
            # `optional`. Migration always regenerates the manifest's own
            # required fields (a file missing them isn't this pack's schema
            # anymore, and un-requiring is not migration's call to make), so
            # these come back required. Not honouring the removal, but not
            # silent about it either. The optional side is informational
            # only (no enforcement consequence either way).
            revived_required = [f for f in manifest_required if f not in old_required]
            # #107: manifest_required and manifest_optional can themselves
            # overlap. Without excluding revived_required here, a field
            # missing from the old file would land in BOTH lists below --
            # revived_manifest_fields would then claim the same field is
            # simultaneously revived-required and revived-optional, the
            # same self-contradiction PR #104's review already closed
            # between preserved_extra_fields and revived_manifest_fields.
            revived_optional = [
                f
                for f in manifest_optional
                if f not in old_required and f not in old_optional and f not in revived_required
            ]

            schema = _build_type_schema(
                pack, node_type, extra_required=extra_required, extra_optional=extra_optional
            )
            content = header + yaml.safe_dump(schema, sort_keys=False, allow_unicode=True)
            path.write_text(content, encoding="utf-8")
            migrated.append(node_type)
            if extra_required or extra_optional:
                preserved_extra_fields[node_type] = {"required": extra_required, "optional": extra_optional}
                logger.info(
                    "Pack '%s': migrated %s, carried over user-added field(s) not in the "
                    "pack manifest -- required=%r optional=%r",
                    name, node_type, extra_required, extra_optional,
                )
            if revived_required or revived_optional:
                revived_manifest_fields[node_type] = {"required": revived_required, "optional": revived_optional}
                logger.warning(
                    "Pack '%s': migrated %s, re-added manifest field(s) that were missing from "
                    "the old file's required/optional lists -- required=%r optional=%r "
                    "(migration does not honour dropping a pack's own fields)",
                    name, node_type, revived_required, revived_optional,
                )
            if not (extra_required or extra_optional or revived_required or revived_optional):
                logger.info("Pack '%s': migrated legacy-shape schema for %s", name, node_type)
            continue
        schema = _build_type_schema(pack, node_type)
        content = header + yaml.safe_dump(schema, sort_keys=False, allow_unicode=True)
        path.write_text(content, encoding="utf-8")
        created.append(node_type)
        logger.info("Pack '%s': created schema for %s", name, node_type)

    # Invalidate loader cache
    try:
        from opencrab.schemas.loader import reload_schema
        for t in created + migrated:
            reload_schema(t)
    except Exception as exc:
        logger.warning("Pack '%s': failed to reload schema cache: %s", name, exc)

    return {
        "pack": name,
        "version": pack.get("version"),
        "created": created,
        "migrated": migrated,
        "skipped": skipped,
        "preserved_extra_fields": preserved_extra_fields,
        "revived_manifest_fields": revived_manifest_fields,
        "total_types": len(pack.get("types", [])),
    }


def uninstall_pack(name: str, force: bool = False) -> dict[str, Any]:
    """
    Remove type schemas generated by a pack.

    Only removes schemas that have `pack: <name>` in their YAML header
    (i.e. were auto-generated). User-customised schemas are kept unless
    force=True.
    """
    pack = get_pack(name)
    if not pack:
        return {"error": f"Pack '{name}' not found."}

    # #109: the delete path is the dangerous one -- vet every type name up
    # front and refuse the whole uninstall rather than removing some files and
    # then hitting a bad name.
    rejected = _unsafe_names(pack.get("types", []) or [])
    if rejected:
        logger.warning("Pack '%s': refusing to uninstall, unsafe type name(s) %r", name, rejected)
        return _unsafe_names_error(name, rejected)

    removed = []
    kept = []

    for node_type in pack.get("types", []):
        path = _TYPES_DIR / f"{node_type}.yaml"
        if not path.exists():
            continue
        # #109 residual guard, re-checked immediately before the unlink: if the
        # path does not demonstrably resolve to a direct child of the type
        # directory, it is kept, never removed.
        if not resolves_inside(path, _TYPES_DIR):
            logger.warning(
                "Pack '%s': %s resolves outside the type directory; keeping it.",
                name, node_type,
            )
            kept.append(node_type)
            continue
        try:
            content = path.read_text(encoding="utf-8")
            is_generated = f"pack: {name}" in content
            if is_generated or force:
                path.unlink()
                removed.append(node_type)
            else:
                kept.append(node_type)
        except Exception as exc:
            logger.warning("Failed to remove schema %s: %s", node_type, exc)
            kept.append(node_type)

    return {
        "pack": name,
        "removed": removed,
        "kept_user_customised": kept,
    }


def _is_pack_installed(name: str, types: list[str]) -> bool:
    """Return True if at least one type from the pack has a schema file.

    An unsafe type name (#109) counts as not installed: such a name could
    never have been written into the type directory in the first place, so
    probing the path it would address is both untrue and an escape.
    """
    return any((_TYPES_DIR / f"{t}.yaml").exists() for t in types if safe_schema_name(t))
