"""
Tests for opencrab.schemas.pack_registry stub generation.

Regression coverage for: generated type stubs used a `node_type/pack/
required/optional` shape that grammar.validator.validate_node_properties
never read (it only looks at `schema.get("properties", {})`), so installed
packs were validated as no-ops. install_pack must emit `type/version/space/
properties` schemas that the validator actually enforces.
"""

from __future__ import annotations

import pytest
import yaml

from opencrab.grammar.validator import validate_node_properties
from opencrab.schemas import loader as schema_loader
from opencrab.schemas import pack_registry


@pytest.fixture
def tmp_pack_env(tmp_path, monkeypatch):
    packs_dir = tmp_path / "packs"
    types_dir = tmp_path / "types"
    packs_dir.mkdir()
    types_dir.mkdir()

    manifest = {
        "name": "testpack",
        "version": "1.0.0",
        "description": "Test pack for stub-format regression coverage.",
        "types": ["Widget"],
        "spaces": ["concept"],
        "type_specs": {
            "Widget": {
                "space": "concept",
                "required": ["name"],
                "optional": ["description"],
            }
        },
    }
    (packs_dir / "testpack.yaml").write_text(yaml.safe_dump(manifest), encoding="utf-8")

    monkeypatch.setattr(pack_registry, "_PACKS_DIR", packs_dir)
    monkeypatch.setattr(pack_registry, "_TYPES_DIR", types_dir)
    monkeypatch.setattr(schema_loader, "SCHEMAS_DIR", types_dir)
    schema_loader.load_type_schema.cache_clear()
    yield types_dir
    schema_loader.load_type_schema.cache_clear()


def test_install_pack_generates_validator_compatible_schema(tmp_pack_env):
    types_dir = tmp_pack_env
    result = pack_registry.install_pack("testpack")
    assert result["created"] == ["Widget"]

    stub_path = types_dir / "Widget.yaml"
    assert stub_path.exists()
    content = stub_path.read_text(encoding="utf-8")
    assert "Auto-generated by schema pack 'testpack'" in content
    assert "pack: testpack" in content  # uninstall's generated-file detection relies on this

    data = yaml.safe_load(content)
    assert data["type"] == "Widget"
    assert data["space"] == "concept"
    assert "properties" in data
    assert data["properties"]["name"]["required"] is True
    assert data["properties"]["description"]["required"] is False
    # codex review round 3 (issue #106): `nullable` duplicated `required`,
    # which is exactly what regressed (required-promotion flipped `required`
    # but not a separately-tracked `nullable`). Generated properties must not
    # carry it at all; the validator derives it from `required` (#49).
    assert "nullable" not in data["properties"]["name"]
    assert "nullable" not in data["properties"]["description"]


def test_validator_enforces_required_property_from_pack_manifest(tmp_pack_env):
    pack_registry.install_pack("testpack")
    schema_loader.load_type_schema.cache_clear()

    missing = validate_node_properties("Widget", {"description": "x"})
    assert missing.valid is False
    assert "name" in missing.error

    ok = validate_node_properties("Widget", {"name": "Foo"})
    assert ok.valid is True


def test_uninstall_removes_generated_stub(tmp_pack_env):
    pack_registry.install_pack("testpack")
    result = pack_registry.uninstall_pack("testpack")
    assert result["removed"] == ["Widget"]
    assert not (tmp_pack_env / "Widget.yaml").exists()


def test_install_pack_migrates_legacy_shape_stub(tmp_pack_env, caplog):
    """install_pack must detect and regenerate a pre-existing legacy-shape
    stub (node_type/pack/required/optional, no `properties`) instead of
    unconditionally skipping it -- that unconditional skip is what made the
    live installed biomedical-pack stubs (issue #38) permanently stuck in
    the shape validate_node_properties can't read.

    This file also demotes the manifest-required `name` field to `optional`
    (`required: []`). Migration always regenerates the manifest's own
    required fields (see test_install_pack_reports_revived_manifest_field
    for why), so `name` comes back required here too -- and PR #104 codex
    review (P2, second round) requires that not be silent: it must show up
    in `revived_manifest_fields`.

    Independent-verifier finding (4th round): `name` must show up ONLY in
    `revived_manifest_fields`, not also in `preserved_extra_fields`. The old
    `extra_optional` filter excluded `manifest_optional` and `extra_required`
    but not `manifest_required`, so a manifest-required field demoted to
    `optional` in the old file was misclassified as a user-added "extra"
    optional field -- the return dict claimed `name` was both a preserved
    user addition (false; nothing was preserved, the demotion was
    overridden) and a revived manifest field (true), contradicting itself
    and the docstring's contract that `preserved_extra_fields` only holds
    fields the manifest doesn't define.
    """
    types_dir = tmp_pack_env
    legacy = {
        "node_type": "Widget",
        "pack": "testpack",
        "required": [],
        "optional": ["name", "description"],
    }
    (types_dir / "Widget.yaml").write_text(
        "# Auto-generated by schema pack 'testpack' v1.0.0\n" + yaml.safe_dump(legacy),
        encoding="utf-8",
    )

    with caplog.at_level("WARNING"):
        result = pack_registry.install_pack("testpack")
    assert result["migrated"] == ["Widget"]
    assert result["created"] == []
    assert result["skipped"] == []
    assert result["revived_manifest_fields"] == {"Widget": {"required": ["name"], "optional": []}}
    assert result["preserved_extra_fields"] == {}
    assert any("re-added manifest field" in rec.message for rec in caplog.records)

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert "properties" in data
    assert data["properties"]["name"]["required"] is True
    assert data["properties"]["description"]["required"] is False

    schema_loader.load_type_schema.cache_clear()
    missing = validate_node_properties("Widget", {"description": "x"})
    assert missing.valid is False
    assert "name" in missing.error


def test_install_pack_does_not_migrate_user_customised_schema(tmp_pack_env):
    """A file with no trace of this pack at all (fully user-authored) must
    be left alone even if it happens to lack `properties` -- migration is
    scoped to files this tool itself generated.
    """
    types_dir = tmp_pack_env
    custom = {"node_type": "Widget", "required": ["name"], "optional": []}
    (types_dir / "Widget.yaml").write_text(yaml.safe_dump(custom), encoding="utf-8")

    result = pack_registry.install_pack("testpack")
    assert result["skipped"] == ["Widget"]
    assert result["migrated"] == []

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data == custom


def test_install_pack_preserves_hand_written_file_that_fakes_pack_field(tmp_pack_env, caplog):
    """The `pack: <name>` YAML field alone is NOT proof install_pack wrote
    the file -- a user can type that field into their own hand-written
    legacy-shape schema too (e.g. copied from a real stub as a starting
    point). Only this tool's own generation-header comment is a safe
    "we produced this" marker. Without it, a legacy-shape file must be left
    untouched (and only warned about), or hand-added constraints like
    required=["name", "sku"] would be silently deleted on reinstall.
    """
    types_dir = tmp_pack_env
    handwritten = {
        "node_type": "Widget",
        "pack": "testpack",
        "required": ["name", "sku"],
        "optional": ["description"],
    }
    # Deliberately no "# Auto-generated by schema pack" header line.
    (types_dir / "Widget.yaml").write_text(yaml.safe_dump(handwritten), encoding="utf-8")

    with caplog.at_level("WARNING"):
        result = pack_registry.install_pack("testpack")

    assert result["migrated"] == []
    assert result["skipped"] == ["Widget"]
    assert result["preserved_extra_fields"] == {}

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data == handwritten  # required=["name", "sku"] survives untouched
    assert any("NOT be auto-migrated" in rec.message for rec in caplog.records)


def test_install_pack_preserves_user_added_field_on_migration(tmp_pack_env, caplog):
    """PR #104 codex review (P1, first round): a generation-header stub can
    still have been hand-edited *after* install -- adding a constraint to a
    previously installed stub is a natural usage pattern. If the field the
    user added (`legacy_only_field`) isn't in the current pack manifest's
    type_specs, migration must carry it into the new `properties` rather
    than drop it -- overwriting a stub that still carries the generation
    header is not licence to discard content the header-check alone can't
    prove is machine-only. Silently dropping it would recreate the exact
    class of bug this issue exists to fix (constraint disappears on
    reinstall).

    PR #104 codex review (P1, second round): legacy shape only ever stored
    a flat field-name list -- it has no per-field type. The preserved field
    must NOT get an invented `type: string`, since grammar.validator now
    actually enforces declared types (#48) and a wrong guess would reject
    real non-string data. See
    test_install_pack_preserved_field_accepts_non_string_value below for
    the regression this exists to prevent.
    """
    types_dir = tmp_pack_env
    legacy = {
        "node_type": "Widget",
        "pack": "testpack",
        "required": ["name", "legacy_only_field"],
        "optional": ["description"],
    }
    (types_dir / "Widget.yaml").write_text(
        "# Auto-generated by schema pack 'testpack' v1.0.0\n" + yaml.safe_dump(legacy),
        encoding="utf-8",
    )

    with caplog.at_level("INFO"):
        result = pack_registry.install_pack("testpack")

    assert result["migrated"] == ["Widget"]
    assert result["preserved_extra_fields"] == {
        "Widget": {"required": ["legacy_only_field"], "optional": []}
    }
    assert result["revived_manifest_fields"] == {}
    assert any("carried over user-added field" in rec.message for rec in caplog.records)

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert "properties" in data
    assert data["properties"]["legacy_only_field"]["required"] is True
    assert "type" not in data["properties"]["legacy_only_field"]  # no guessed type
    assert "nullable" not in data["properties"]["legacy_only_field"]  # no guessed nullability
    assert data["properties"]["name"]["required"] is True
    assert data["properties"]["description"]["required"] is False

    # The preserved field is actually enforced (presence/required-ness) now,
    # not just present in the file.
    schema_loader.load_type_schema.cache_clear()
    missing = validate_node_properties("Widget", {"name": "Foo", "description": "x"})
    assert missing.valid is False
    assert "legacy_only_field" in missing.error


def test_install_pack_promoted_optional_field_has_no_nullable(tmp_pack_env):
    """codex review round 3: `description` is manifest-optional. A legacy
    stub whose `required` list already includes it (i.e. the user promoted
    it by hand) goes through the *extra_required* "field already in
    properties -> flip required to True" path in `_build_type_schema`.
    Before this fix that path only flipped `required` and left the
    `nullable: True` written by the optional-fields loop untouched, so the
    migrated schema said required=True and nullable=True for the same
    field -- a self-contradiction, and a regression from the pre-#38
    behaviour where a required field was always non-nullable. Since
    `nullable` is gone entirely now, the promoted field is just
    required=True with no nullable key to contradict it, and the validator
    derives non-nullable from required=True (#49).
    """
    types_dir = tmp_pack_env
    legacy = {
        "node_type": "Widget",
        "pack": "testpack",
        "required": ["name", "description"],  # description promoted by hand
        "optional": [],
    }
    (types_dir / "Widget.yaml").write_text(
        "# Auto-generated by schema pack 'testpack' v1.0.0\n" + yaml.safe_dump(legacy),
        encoding="utf-8",
    )

    pack_registry.install_pack("testpack")

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data["properties"]["description"] == {"type": "string", "required": True}
    assert "nullable" not in data["properties"]["description"]


def test_install_pack_preserved_field_accepts_non_string_value(tmp_pack_env):
    """PR #104 codex review (P1, second round) -- the core regression.

    grammar.validator.validate_node_properties#_value_matches_type rejects
    a value that doesn't match a `type` the schema declares. Confirmed by
    reading validator.py directly: `declared_type = spec.get("type")`, and
    the type-check loop only runs `if declared_type is not None`. So a
    preserved field with NO `type` key skips the type check entirely --
    the field's presence/required-ness is still enforced, but its value is
    never type-checked. If migration had instead guessed `type: string`
    (the pre-fix behaviour), this exact call would fail with "must be of
    type 'string', got int" for a real, valid integer value like a price.
    """
    types_dir = tmp_pack_env
    legacy = {
        "node_type": "Widget",
        "pack": "testpack",
        "required": ["name", "price"],
        "optional": [],
    }
    (types_dir / "Widget.yaml").write_text(
        "# Auto-generated by schema pack 'testpack' v1.0.0\n" + yaml.safe_dump(legacy),
        encoding="utf-8",
    )
    pack_registry.install_pack("testpack")
    schema_loader.load_type_schema.cache_clear()

    ok = validate_node_properties("Widget", {"name": "Widget A", "price": 42})
    assert ok.valid is True, ok.error


def test_install_pack_continues_past_unreadable_existing_file(tmp_path, monkeypatch):
    """PR #104 codex review (P2): `path.read_text()` for an existing file used
    to sit outside the try/except that only wrapped `yaml.safe_load`, so a
    file with invalid UTF-8 (or any other read error) raised out of the loop
    and aborted the whole pack install -- every other type in the pack was
    left uninstalled too. One bad file must only skip that one type.
    """
    packs_dir = tmp_path / "packs"
    types_dir = tmp_path / "types"
    packs_dir.mkdir()
    types_dir.mkdir()

    manifest = {
        "name": "twotype",
        "version": "1.0.0",
        "types": ["Widget", "Gadget"],
        "spaces": ["concept"],
        "type_specs": {
            "Widget": {"space": "concept", "required": ["name"], "optional": []},
            "Gadget": {"space": "concept", "required": ["name"], "optional": []},
        },
    }
    (packs_dir / "twotype.yaml").write_text(yaml.safe_dump(manifest), encoding="utf-8")
    monkeypatch.setattr(pack_registry, "_PACKS_DIR", packs_dir)
    monkeypatch.setattr(pack_registry, "_TYPES_DIR", types_dir)

    # Invalid UTF-8 byte sequence -- read_text(encoding="utf-8") raises.
    (types_dir / "Widget.yaml").write_bytes(b"\xff\xfe not valid utf-8")

    result = pack_registry.install_pack("twotype")
    assert result["skipped"] == ["Widget"]
    assert result["created"] == ["Gadget"]
    assert (types_dir / "Gadget.yaml").exists()


def test_install_pack_skips_non_dict_yaml_without_crashing(tmp_pack_env):
    """A pre-existing file that's valid YAML but not a mapping (e.g. a bare
    list) must not crash install_pack -- previously every existing file was
    unconditionally skipped, so this shape was never exercised.
    """
    types_dir = tmp_pack_env
    (types_dir / "Widget.yaml").write_text("- just\n- a\n- list\n", encoding="utf-8")

    result = pack_registry.install_pack("testpack")
    assert result["migrated"] == []
    assert result["skipped"] == ["Widget"]


def test_load_type_schema_warns_on_legacy_shape(tmp_pack_env, caplog):
    types_dir = tmp_pack_env
    legacy = {"node_type": "Widget", "pack": "testpack", "required": [], "optional": ["name"]}
    (types_dir / "Widget.yaml").write_text(yaml.safe_dump(legacy), encoding="utf-8")

    schema_loader.load_type_schema.cache_clear()
    with caplog.at_level("WARNING"):
        schema_loader.load_type_schema("Widget")
    assert any("legacy shape" in rec.message for rec in caplog.records)


def test_installed_pack_stub_files_have_current_shape():
    """Live-directory regression check for issue #38.

    schema_pack_install artifacts (schemas/types/*.yaml with a `pack:`
    field) are gitignored, so a fresh checkout/CI runner normally has none
    of them -- only the hand-written core types. In that case there is
    nothing to check, and this must SKIP rather than pass, because a silent
    pass here is indistinguishable from "verified clean" -- which is
    exactly the kind of false confidence that let the original stale-stub
    bug go unnoticed. The tmp_path-fixture tests above
    (test_install_pack_migrates_legacy_shape_stub etc.) are what actually
    exercise the detection/migration logic in CI; this test only adds value
    in an environment (e.g. a real local install) that has pack-generated
    files on disk.
    """
    generated = [
        (path, data)
        for path in sorted(schema_loader.SCHEMAS_DIR.glob("*.yaml"))
        if isinstance((data := yaml.safe_load(path.read_text(encoding="utf-8"))), dict)
        and data.get("pack")
    ]
    if not generated:
        pytest.skip(
            "no pack-generated schema stubs present in this checkout "
            "(schema_pack_install output is gitignored) -- nothing to scan here"
        )

    stale = [path.name for path, data in generated if "properties" not in data]
    assert stale == [], f"legacy-shape schema stub(s) found, run install_pack to migrate: {stale}"


def _install_overlap_pack(tmp_path, monkeypatch, existing_widget_file=None):
    """Set up a pack whose manifest declares the same field in both
    `required` and `optional` (issue #107), optionally with a pre-existing
    legacy-shape Widget.yaml to route install_pack through the migration
    branch instead of the fresh-create branch.
    """
    packs_dir = tmp_path / "packs"
    types_dir = tmp_path / "types"
    packs_dir.mkdir()
    types_dir.mkdir()

    manifest = {
        "name": "overlappack",
        "version": "1.0.0",
        "types": ["Widget"],
        "spaces": ["concept"],
        "type_specs": {
            "Widget": {
                "space": "concept",
                "required": ["name"],
                "optional": ["name", "description"],  # #107: same field, both lists
            }
        },
    }
    (packs_dir / "overlappack.yaml").write_text(yaml.safe_dump(manifest), encoding="utf-8")
    monkeypatch.setattr(pack_registry, "_PACKS_DIR", packs_dir)
    monkeypatch.setattr(pack_registry, "_TYPES_DIR", types_dir)
    monkeypatch.setattr(schema_loader, "SCHEMAS_DIR", types_dir)
    schema_loader.load_type_schema.cache_clear()

    if existing_widget_file is not None:
        (types_dir / "Widget.yaml").write_text(existing_widget_file, encoding="utf-8")

    return types_dir


def test_install_pack_required_wins_over_manifest_optional_overlap(tmp_path, monkeypatch):
    """Issue #107: manifest `type_specs.Widget` lists `name` in BOTH
    `required` and `optional`. `_build_type_schema`'s optional-fields loop
    used to overwrite whatever the required-fields loop wrote, with no
    existence check -- unlike the `extra_required`/`extra_optional` handling
    a few lines down in the same function, which already guards with
    `if field_name in/not in properties`. required must win here too.
    """
    types_dir = _install_overlap_pack(tmp_path, monkeypatch)
    result = pack_registry.install_pack("overlappack")
    assert result["created"] == ["Widget"]

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data["properties"]["name"]["required"] is True
    assert data["properties"]["description"]["required"] is False

    schema_loader.load_type_schema.cache_clear()
    missing = validate_node_properties("Widget", {"description": "x"})
    assert missing.valid is False
    assert "name" in missing.error


def test_install_pack_warns_on_manifest_required_optional_overlap(tmp_path, monkeypatch, caplog):
    """Issue #107 asks that the contradiction itself be surfaced, not just
    silently resolved in required's favour -- a pack author who lists the
    same field twice made a mistake and should be told.
    """
    _install_overlap_pack(tmp_path, monkeypatch)
    with caplog.at_level("WARNING"):
        pack_registry.install_pack("overlappack")
    assert any(
        "name" in rec.message and "required" in rec.message and "optional" in rec.message
        for rec in caplog.records
    )


def test_install_pack_migration_report_does_not_contradict_itself_on_overlap(tmp_path, monkeypatch, caplog):
    """Issue #107 (codex design-review round 1 counterexample): the
    migration branch computes `revived_required`/`revived_optional`
    independently from the manifest's `required`/`optional` lists. When
    those two manifest lists themselves overlap on a field missing from the
    old on-disk file, both `revived_required` and `revived_optional` used
    to include that field -- `revived_manifest_fields` then reported `name`
    as simultaneously revived-required and revived-optional, contradicting
    itself (the same class of contradiction PR #104's review already closed
    between `preserved_extra_fields` and `revived_manifest_fields`).
    """
    legacy = {
        "node_type": "Widget",
        "pack": "overlappack",
        "required": [],
        "optional": ["description"],  # old file never had `name` at all
    }
    existing = "# Auto-generated by schema pack 'overlappack' v1.0.0\n" + yaml.safe_dump(legacy)
    types_dir = _install_overlap_pack(tmp_path, monkeypatch, existing_widget_file=existing)

    with caplog.at_level("WARNING"):
        result = pack_registry.install_pack("overlappack")
    assert result["migrated"] == ["Widget"]

    revived = result["revived_manifest_fields"]["Widget"]
    assert "name" in revived["required"]
    assert "name" not in revived["optional"]  # must not claim `name` both ways

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data["properties"]["name"]["required"] is True


def _install_stale_current_shape_pack(tmp_path, monkeypatch, existing_widget_file, pack_name="overlappack"):
    """Set up a pack manifest (required=["name"], optional=["name","description"])
    with a pre-existing Widget.yaml already in CURRENT shape (has `properties`,
    so `_is_legacy_shape` is False) -- simulating a schema generated by a
    pre-#107-fix install where the overlap bug already wrote
    `required: false` for `name`.
    """
    packs_dir = tmp_path / "packs"
    types_dir = tmp_path / "types"
    packs_dir.mkdir()
    types_dir.mkdir()

    manifest = {
        "name": pack_name,
        "version": "1.0.0",
        "types": ["Widget"],
        "spaces": ["concept"],
        "type_specs": {
            "Widget": {
                "space": "concept",
                "required": ["name"],
                "optional": ["name", "description"],
            }
        },
    }
    (packs_dir / f"{pack_name}.yaml").write_text(yaml.safe_dump(manifest), encoding="utf-8")
    monkeypatch.setattr(pack_registry, "_PACKS_DIR", packs_dir)
    monkeypatch.setattr(pack_registry, "_TYPES_DIR", types_dir)
    monkeypatch.setattr(schema_loader, "SCHEMAS_DIR", types_dir)
    schema_loader.load_type_schema.cache_clear()

    (types_dir / "Widget.yaml").write_text(existing_widget_file, encoding="utf-8")
    return types_dir


def test_install_pack_repairs_stale_current_shape_schema_from_before_fix(tmp_path, monkeypatch):
    """Issue #107 (codex review, PR #336, P1): a schema generated BEFORE this
    fix already has `properties["name"]["required"] == False` on disk (the
    overlap bug's output). `install_pack` used to skip every current-shape
    file unconditionally (355-357), so a bare reinstall never reached the
    fixed `_build_type_schema` and the stale False persisted forever. A
    reinstall must repair it.
    """
    stale = (
        "# Auto-generated by schema pack 'overlappack' v1.0.0\n"
        + yaml.safe_dump(
            {
                "type": "Widget",
                "version": "1.0.0",
                "space": "concept",
                "pack": "overlappack",
                "properties": {
                    "name": {"type": "string", "required": False},
                    "description": {"type": "string", "required": False},
                },
            },
            sort_keys=False,
        )
    )
    types_dir = _install_stale_current_shape_pack(tmp_path, monkeypatch, stale)

    result = pack_registry.install_pack("overlappack")
    assert "Widget" in result["migrated"]

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data["properties"]["name"]["required"] is True
    assert data["properties"]["description"]["required"] is False

    schema_loader.load_type_schema.cache_clear()
    missing = validate_node_properties("Widget", {"description": "x"})
    assert missing.valid is False
    assert "name" in missing.error


def test_install_pack_warns_on_repairing_stale_current_shape_schema(tmp_path, monkeypatch, caplog):
    """The repair must be visible in the logs, like the fresh-install and
    migration-report warnings added for #107 -- a pack author or operator
    should know a previously-installed schema just got its required flag
    corrected.
    """
    stale = (
        "# Auto-generated by schema pack 'overlappack' v1.0.0\n"
        + yaml.safe_dump(
            {
                "type": "Widget",
                "version": "1.0.0",
                "space": "concept",
                "pack": "overlappack",
                "properties": {
                    "name": {"type": "string", "required": False},
                    "description": {"type": "string", "required": False},
                },
            },
            sort_keys=False,
        )
    )
    _install_stale_current_shape_pack(tmp_path, monkeypatch, stale)

    with caplog.at_level("WARNING"):
        pack_registry.install_pack("overlappack")
    # Field list and type name must not swap places in the formatted
    # message (codex review, PR #336 round 2: a %r/%s argument-order bug
    # produced "field(s) 'Widget' for ['name']" -- type and field list
    # transposed -- and this assertion's earlier form, checking only that
    # both substrings appeared anywhere, did not catch it).
    assert any(
        "repaired" in rec.message.lower() and "['name'] for Widget" in rec.message
        for rec in caplog.records
    )


def test_install_pack_does_not_touch_healthy_current_shape_schema(tmp_path, monkeypatch):
    """Regression guard: a current-shape schema with no stale required=False
    (e.g. generated by an already-fixed install, or a manifest with no
    overlap) must still be skipped and left byte-for-byte untouched, exactly
    as before this change.
    """
    healthy = (
        "# Auto-generated by schema pack 'overlappack' v1.0.0\n"
        + yaml.safe_dump(
            {
                "type": "Widget",
                "version": "1.0.0",
                "space": "concept",
                "pack": "overlappack",
                "properties": {
                    "name": {"type": "string", "required": True},
                    "description": {"type": "string", "required": False},
                },
            },
            sort_keys=False,
        )
    )
    types_dir = _install_stale_current_shape_pack(tmp_path, monkeypatch, healthy)
    before = (types_dir / "Widget.yaml").read_text(encoding="utf-8")

    result = pack_registry.install_pack("overlappack")
    assert result["skipped"] == ["Widget"]

    after = (types_dir / "Widget.yaml").read_text(encoding="utf-8")
    assert after == before


def test_install_pack_does_not_repair_hand_written_current_shape_schema(tmp_path, monkeypatch):
    """Safety guard: a current-shape file with no generation header (hand-
    written, or copy-pasted) must not be auto-repaired even if it has a
    stale-looking required=False -- same safety bar as the legacy-migration
    path's `_has_generation_marker` check.
    """
    hand_written = yaml.safe_dump(
        {
            "type": "Widget",
            "version": "1.0.0",
            "space": "concept",
            "pack": "overlappack",
            "properties": {
                "name": {"type": "string", "required": False},
                "description": {"type": "string", "required": False},
            },
        },
        sort_keys=False,
    )
    types_dir = _install_stale_current_shape_pack(tmp_path, monkeypatch, hand_written)
    before = (types_dir / "Widget.yaml").read_text(encoding="utf-8")

    result = pack_registry.install_pack("overlappack")
    assert result["skipped"] == ["Widget"]

    after = (types_dir / "Widget.yaml").read_text(encoding="utf-8")
    assert after == before
