"""
Tests for opencrab.schemas.pack_registry stub generation.

Regression coverage for: generated type stubs used a `node_type/pack/
required/optional` shape that grammar.validator.validate_node_properties
never read (it only looks at `schema.get("properties", {})`), so installed
packs were validated as no-ops. install_pack must emit `type/version/space/
properties` schemas that the validator actually enforces.
"""

from __future__ import annotations

import pytest
import yaml

from opencrab.grammar.validator import validate_node_properties
from opencrab.schemas import loader as schema_loader
from opencrab.schemas import pack_registry


@pytest.fixture
def tmp_pack_env(tmp_path, monkeypatch):
    packs_dir = tmp_path / "packs"
    types_dir = tmp_path / "types"
    packs_dir.mkdir()
    types_dir.mkdir()

    manifest = {
        "name": "testpack",
        "version": "1.0.0",
        "description": "Test pack for stub-format regression coverage.",
        "types": ["Widget"],
        "spaces": ["concept"],
        "type_specs": {
            "Widget": {
                "space": "concept",
                "required": ["name"],
                "optional": ["description"],
            }
        },
    }
    (packs_dir / "testpack.yaml").write_text(yaml.safe_dump(manifest), encoding="utf-8")

    monkeypatch.setattr(pack_registry, "_PACKS_DIR", packs_dir)
    monkeypatch.setattr(pack_registry, "_TYPES_DIR", types_dir)
    monkeypatch.setattr(schema_loader, "SCHEMAS_DIR", types_dir)
    schema_loader.load_type_schema.cache_clear()
    yield types_dir
    schema_loader.load_type_schema.cache_clear()


def test_install_pack_generates_validator_compatible_schema(tmp_pack_env):
    types_dir = tmp_pack_env
    result = pack_registry.install_pack("testpack")
    assert result["created"] == ["Widget"]

    stub_path = types_dir / "Widget.yaml"
    assert stub_path.exists()
    content = stub_path.read_text(encoding="utf-8")
    assert "Auto-generated by schema pack 'testpack'" in content
    assert "pack: testpack" in content  # uninstall's generated-file detection relies on this

    data = yaml.safe_load(content)
    assert data["type"] == "Widget"
    assert data["space"] == "concept"
    assert "properties" in data
    assert data["properties"]["name"]["required"] is True
    assert data["properties"]["description"]["required"] is False


def test_validator_enforces_required_property_from_pack_manifest(tmp_pack_env):
    pack_registry.install_pack("testpack")
    schema_loader.load_type_schema.cache_clear()

    missing = validate_node_properties("Widget", {"description": "x"})
    assert missing.valid is False
    assert "name" in missing.error

    ok = validate_node_properties("Widget", {"name": "Foo"})
    assert ok.valid is True


def test_uninstall_removes_generated_stub(tmp_pack_env):
    pack_registry.install_pack("testpack")
    result = pack_registry.uninstall_pack("testpack")
    assert result["removed"] == ["Widget"]
    assert not (tmp_pack_env / "Widget.yaml").exists()


def test_install_pack_migrates_legacy_shape_stub(tmp_pack_env):
    """install_pack must detect and regenerate a pre-existing legacy-shape
    stub (node_type/pack/required/optional, no `properties`) instead of
    unconditionally skipping it -- that unconditional skip is what made the
    live installed biomedical-pack stubs (issue #38) permanently stuck in
    the shape validate_node_properties can't read.
    """
    types_dir = tmp_pack_env
    legacy = {
        "node_type": "Widget",
        "pack": "testpack",
        "required": [],
        "optional": ["name", "description"],
    }
    (types_dir / "Widget.yaml").write_text(
        "# Auto-generated by schema pack 'testpack' v1.0.0\n" + yaml.safe_dump(legacy),
        encoding="utf-8",
    )

    result = pack_registry.install_pack("testpack")
    assert result["migrated"] == ["Widget"]
    assert result["created"] == []
    assert result["skipped"] == []

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert "properties" in data
    assert data["properties"]["name"]["required"] is True
    assert data["properties"]["description"]["required"] is False

    schema_loader.load_type_schema.cache_clear()
    missing = validate_node_properties("Widget", {"description": "x"})
    assert missing.valid is False
    assert "name" in missing.error


def test_install_pack_does_not_migrate_user_customised_schema(tmp_pack_env):
    """A file without this pack's `pack:` header (i.e. user-authored, not
    pack-generated) must be left alone even if it happens to lack
    `properties` -- migration is scoped to this pack's own legacy stubs.
    """
    types_dir = tmp_pack_env
    custom = {"node_type": "Widget", "required": ["name"], "optional": []}
    (types_dir / "Widget.yaml").write_text(yaml.safe_dump(custom), encoding="utf-8")

    result = pack_registry.install_pack("testpack")
    assert result["skipped"] == ["Widget"]
    assert result["migrated"] == []

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data == custom


def test_load_type_schema_warns_on_legacy_shape(tmp_pack_env, caplog):
    types_dir = tmp_pack_env
    legacy = {"node_type": "Widget", "pack": "testpack", "required": [], "optional": ["name"]}
    (types_dir / "Widget.yaml").write_text(yaml.safe_dump(legacy), encoding="utf-8")

    schema_loader.load_type_schema.cache_clear()
    with caplog.at_level("WARNING"):
        schema_loader.load_type_schema("Widget")
    assert any("legacy shape" in rec.message for rec in caplog.records)


def test_every_installed_type_schema_has_current_shape():
    """Cluster-wide prevention (issue #38 lead analysis): a generator that
    was updated to emit `properties` is useless if stale on-disk artifacts
    from an older generator version are never checked. This scans every
    real file under schemas/types/ -- not a tmp_path sandbox -- so a stale
    installed pack stub (legacy `required`/`optional` without `properties`)
    fails CI instead of silently no-opping validation forever.
    """
    stale = [
        path.name
        for path in sorted(schema_loader.SCHEMAS_DIR.glob("*.yaml"))
        if (data := yaml.safe_load(path.read_text(encoding="utf-8")))
        and "properties" not in data
        and ("required" in data or "optional" in data)
    ]
    assert stale == [], f"legacy-shape schema stub(s) found, run install_pack to migrate: {stale}"
