"""
Tests for opencrab.schemas.pack_registry stub generation.

Regression coverage for: generated type stubs used a `node_type/pack/
required/optional` shape that grammar.validator.validate_node_properties
never read (it only looks at `schema.get("properties", {})`), so installed
packs were validated as no-ops. install_pack must emit `type/version/space/
properties` schemas that the validator actually enforces.
"""

from __future__ import annotations

import pytest
import yaml

from opencrab.grammar.validator import validate_node_properties
from opencrab.schemas import loader as schema_loader
from opencrab.schemas import pack_registry


@pytest.fixture
def tmp_pack_env(tmp_path, monkeypatch):
    packs_dir = tmp_path / "packs"
    types_dir = tmp_path / "types"
    packs_dir.mkdir()
    types_dir.mkdir()

    manifest = {
        "name": "testpack",
        "version": "1.0.0",
        "description": "Test pack for stub-format regression coverage.",
        "types": ["Widget"],
        "spaces": ["concept"],
        "type_specs": {
            "Widget": {
                "space": "concept",
                "required": ["name"],
                "optional": ["description"],
            }
        },
    }
    (packs_dir / "testpack.yaml").write_text(yaml.safe_dump(manifest), encoding="utf-8")

    monkeypatch.setattr(pack_registry, "_PACKS_DIR", packs_dir)
    monkeypatch.setattr(pack_registry, "_TYPES_DIR", types_dir)
    monkeypatch.setattr(schema_loader, "SCHEMAS_DIR", types_dir)
    schema_loader.load_type_schema.cache_clear()
    yield types_dir
    schema_loader.load_type_schema.cache_clear()


def test_install_pack_generates_validator_compatible_schema(tmp_pack_env):
    types_dir = tmp_pack_env
    result = pack_registry.install_pack("testpack")
    assert result["created"] == ["Widget"]

    stub_path = types_dir / "Widget.yaml"
    assert stub_path.exists()
    content = stub_path.read_text(encoding="utf-8")
    assert "Auto-generated by schema pack 'testpack'" in content
    assert "pack: testpack" in content  # uninstall's generated-file detection relies on this

    data = yaml.safe_load(content)
    assert data["type"] == "Widget"
    assert data["space"] == "concept"
    assert "properties" in data
    assert data["properties"]["name"]["required"] is True
    assert data["properties"]["description"]["required"] is False
    # codex review round 3 (issue #106): `nullable` duplicated `required`,
    # which is exactly what regressed (required-promotion flipped `required`
    # but not a separately-tracked `nullable`). Generated properties must not
    # carry it at all; the validator derives it from `required` (#49).
    assert "nullable" not in data["properties"]["name"]
    assert "nullable" not in data["properties"]["description"]


def test_validator_enforces_required_property_from_pack_manifest(tmp_pack_env):
    pack_registry.install_pack("testpack")
    schema_loader.load_type_schema.cache_clear()

    missing = validate_node_properties("Widget", {"description": "x"})
    assert missing.valid is False
    assert "name" in missing.error

    ok = validate_node_properties("Widget", {"name": "Foo"})
    assert ok.valid is True


def test_uninstall_removes_generated_stub(tmp_pack_env):
    pack_registry.install_pack("testpack")
    result = pack_registry.uninstall_pack("testpack")
    assert result["removed"] == ["Widget"]
    assert not (tmp_pack_env / "Widget.yaml").exists()


def test_install_pack_migrates_legacy_shape_stub(tmp_pack_env, caplog):
    """install_pack must detect and regenerate a pre-existing legacy-shape
    stub (node_type/pack/required/optional, no `properties`) instead of
    unconditionally skipping it -- that unconditional skip is what made the
    live installed biomedical-pack stubs (issue #38) permanently stuck in
    the shape validate_node_properties can't read.

    This file also demotes the manifest-required `name` field to `optional`
    (`required: []`). Migration always regenerates the manifest's own
    required fields (see test_install_pack_reports_revived_manifest_field
    for why), so `name` comes back required here too -- and PR #104 codex
    review (P2, second round) requires that not be silent: it must show up
    in `revived_manifest_fields`.

    Independent-verifier finding (4th round): `name` must show up ONLY in
    `revived_manifest_fields`, not also in `preserved_extra_fields`. The old
    `extra_optional` filter excluded `manifest_optional` and `extra_required`
    but not `manifest_required`, so a manifest-required field demoted to
    `optional` in the old file was misclassified as a user-added "extra"
    optional field -- the return dict claimed `name` was both a preserved
    user addition (false; nothing was preserved, the demotion was
    overridden) and a revived manifest field (true), contradicting itself
    and the docstring's contract that `preserved_extra_fields` only holds
    fields the manifest doesn't define.
    """
    types_dir = tmp_pack_env
    legacy = {
        "node_type": "Widget",
        "pack": "testpack",
        "required": [],
        "optional": ["name", "description"],
    }
    (types_dir / "Widget.yaml").write_text(
        "# Auto-generated by schema pack 'testpack' v1.0.0\n" + yaml.safe_dump(legacy),
        encoding="utf-8",
    )

    with caplog.at_level("WARNING"):
        result = pack_registry.install_pack("testpack")
    assert result["migrated"] == ["Widget"]
    assert result["created"] == []
    assert result["skipped"] == []
    assert result["revived_manifest_fields"] == {"Widget": {"required": ["name"], "optional": []}}
    assert result["preserved_extra_fields"] == {}
    assert any("re-added manifest field" in rec.message for rec in caplog.records)

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert "properties" in data
    assert data["properties"]["name"]["required"] is True
    assert data["properties"]["description"]["required"] is False

    schema_loader.load_type_schema.cache_clear()
    missing = validate_node_properties("Widget", {"description": "x"})
    assert missing.valid is False
    assert "name" in missing.error


def test_install_pack_does_not_migrate_user_customised_schema(tmp_pack_env):
    """A file with no trace of this pack at all (fully user-authored) must
    be left alone even if it happens to lack `properties` -- migration is
    scoped to files this tool itself generated.
    """
    types_dir = tmp_pack_env
    custom = {"node_type": "Widget", "required": ["name"], "optional": []}
    (types_dir / "Widget.yaml").write_text(yaml.safe_dump(custom), encoding="utf-8")

    result = pack_registry.install_pack("testpack")
    assert result["skipped"] == ["Widget"]
    assert result["migrated"] == []

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data == custom


def test_install_pack_preserves_hand_written_file_that_fakes_pack_field(tmp_pack_env, caplog):
    """The `pack: <name>` YAML field alone is NOT proof install_pack wrote
    the file -- a user can type that field into their own hand-written
    legacy-shape schema too (e.g. copied from a real stub as a starting
    point). Only this tool's own generation-header comment is a safe
    "we produced this" marker. Without it, a legacy-shape file must be left
    untouched (and only warned about), or hand-added constraints like
    required=["name", "sku"] would be silently deleted on reinstall.
    """
    types_dir = tmp_pack_env
    handwritten = {
        "node_type": "Widget",
        "pack": "testpack",
        "required": ["name", "sku"],
        "optional": ["description"],
    }
    # Deliberately no "# Auto-generated by schema pack" header line.
    (types_dir / "Widget.yaml").write_text(yaml.safe_dump(handwritten), encoding="utf-8")

    with caplog.at_level("WARNING"):
        result = pack_registry.install_pack("testpack")

    assert result["migrated"] == []
    assert result["skipped"] == ["Widget"]
    assert result["preserved_extra_fields"] == {}

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data == handwritten  # required=["name", "sku"] survives untouched
    assert any("NOT be auto-migrated" in rec.message for rec in caplog.records)


def test_install_pack_preserves_user_added_field_on_migration(tmp_pack_env, caplog):
    """PR #104 codex review (P1, first round): a generation-header stub can
    still have been hand-edited *after* install -- adding a constraint to a
    previously installed stub is a natural usage pattern. If the field the
    user added (`legacy_only_field`) isn't in the current pack manifest's
    type_specs, migration must carry it into the new `properties` rather
    than drop it -- overwriting a stub that still carries the generation
    header is not licence to discard content the header-check alone can't
    prove is machine-only. Silently dropping it would recreate the exact
    class of bug this issue exists to fix (constraint disappears on
    reinstall).

    PR #104 codex review (P1, second round): legacy shape only ever stored
    a flat field-name list -- it has no per-field type. The preserved field
    must NOT get an invented `type: string`, since grammar.validator now
    actually enforces declared types (#48) and a wrong guess would reject
    real non-string data. See
    test_install_pack_preserved_field_accepts_non_string_value below for
    the regression this exists to prevent.
    """
    types_dir = tmp_pack_env
    legacy = {
        "node_type": "Widget",
        "pack": "testpack",
        "required": ["name", "legacy_only_field"],
        "optional": ["description"],
    }
    (types_dir / "Widget.yaml").write_text(
        "# Auto-generated by schema pack 'testpack' v1.0.0\n" + yaml.safe_dump(legacy),
        encoding="utf-8",
    )

    with caplog.at_level("INFO"):
        result = pack_registry.install_pack("testpack")

    assert result["migrated"] == ["Widget"]
    assert result["preserved_extra_fields"] == {
        "Widget": {"required": ["legacy_only_field"], "optional": []}
    }
    assert result["revived_manifest_fields"] == {}
    assert any("carried over user-added field" in rec.message for rec in caplog.records)

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert "properties" in data
    assert data["properties"]["legacy_only_field"]["required"] is True
    assert "type" not in data["properties"]["legacy_only_field"]  # no guessed type
    assert "nullable" not in data["properties"]["legacy_only_field"]  # no guessed nullability
    assert data["properties"]["name"]["required"] is True
    assert data["properties"]["description"]["required"] is False

    # The preserved field is actually enforced (presence/required-ness) now,
    # not just present in the file.
    schema_loader.load_type_schema.cache_clear()
    missing = validate_node_properties("Widget", {"name": "Foo", "description": "x"})
    assert missing.valid is False
    assert "legacy_only_field" in missing.error


def test_install_pack_promoted_optional_field_has_no_nullable(tmp_pack_env):
    """codex review round 3: `description` is manifest-optional. A legacy
    stub whose `required` list already includes it (i.e. the user promoted
    it by hand) goes through the *extra_required* "field already in
    properties -> flip required to True" path in `_build_type_schema`.
    Before this fix that path only flipped `required` and left the
    `nullable: True` written by the optional-fields loop untouched, so the
    migrated schema said required=True and nullable=True for the same
    field -- a self-contradiction, and a regression from the pre-#38
    behaviour where a required field was always non-nullable. Since
    `nullable` is gone entirely now, the promoted field is just
    required=True with no nullable key to contradict it, and the validator
    derives non-nullable from required=True (#49).
    """
    types_dir = tmp_pack_env
    legacy = {
        "node_type": "Widget",
        "pack": "testpack",
        "required": ["name", "description"],  # description promoted by hand
        "optional": [],
    }
    (types_dir / "Widget.yaml").write_text(
        "# Auto-generated by schema pack 'testpack' v1.0.0\n" + yaml.safe_dump(legacy),
        encoding="utf-8",
    )

    pack_registry.install_pack("testpack")

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data["properties"]["description"] == {"type": "string", "required": True}
    assert "nullable" not in data["properties"]["description"]


def test_install_pack_preserved_field_accepts_non_string_value(tmp_pack_env):
    """PR #104 codex review (P1, second round) -- the core regression.

    grammar.validator.validate_node_properties#_value_matches_type rejects
    a value that doesn't match a `type` the schema declares. Confirmed by
    reading validator.py directly: `declared_type = spec.get("type")`, and
    the type-check loop only runs `if declared_type is not None`. So a
    preserved field with NO `type` key skips the type check entirely --
    the field's presence/required-ness is still enforced, but its value is
    never type-checked. If migration had instead guessed `type: string`
    (the pre-fix behaviour), this exact call would fail with "must be of
    type 'string', got int" for a real, valid integer value like a price.
    """
    types_dir = tmp_pack_env
    legacy = {
        "node_type": "Widget",
        "pack": "testpack",
        "required": ["name", "price"],
        "optional": [],
    }
    (types_dir / "Widget.yaml").write_text(
        "# Auto-generated by schema pack 'testpack' v1.0.0\n" + yaml.safe_dump(legacy),
        encoding="utf-8",
    )
    pack_registry.install_pack("testpack")
    schema_loader.load_type_schema.cache_clear()

    ok = validate_node_properties("Widget", {"name": "Widget A", "price": 42})
    assert ok.valid is True, ok.error


def test_install_pack_continues_past_unreadable_existing_file(tmp_path, monkeypatch):
    """PR #104 codex review (P2): `path.read_text()` for an existing file used
    to sit outside the try/except that only wrapped `yaml.safe_load`, so a
    file with invalid UTF-8 (or any other read error) raised out of the loop
    and aborted the whole pack install -- every other type in the pack was
    left uninstalled too. One bad file must only skip that one type.
    """
    packs_dir = tmp_path / "packs"
    types_dir = tmp_path / "types"
    packs_dir.mkdir()
    types_dir.mkdir()

    manifest = {
        "name": "twotype",
        "version": "1.0.0",
        "types": ["Widget", "Gadget"],
        "spaces": ["concept"],
        "type_specs": {
            "Widget": {"space": "concept", "required": ["name"], "optional": []},
            "Gadget": {"space": "concept", "required": ["name"], "optional": []},
        },
    }
    (packs_dir / "twotype.yaml").write_text(yaml.safe_dump(manifest), encoding="utf-8")
    monkeypatch.setattr(pack_registry, "_PACKS_DIR", packs_dir)
    monkeypatch.setattr(pack_registry, "_TYPES_DIR", types_dir)

    # Invalid UTF-8 byte sequence -- read_text(encoding="utf-8") raises.
    (types_dir / "Widget.yaml").write_bytes(b"\xff\xfe not valid utf-8")

    result = pack_registry.install_pack("twotype")
    assert result["skipped"] == ["Widget"]
    assert result["created"] == ["Gadget"]
    assert (types_dir / "Gadget.yaml").exists()


def test_install_pack_skips_non_dict_yaml_without_crashing(tmp_pack_env):
    """A pre-existing file that's valid YAML but not a mapping (e.g. a bare
    list) must not crash install_pack -- previously every existing file was
    unconditionally skipped, so this shape was never exercised.
    """
    types_dir = tmp_pack_env
    (types_dir / "Widget.yaml").write_text("- just\n- a\n- list\n", encoding="utf-8")

    result = pack_registry.install_pack("testpack")
    assert result["migrated"] == []
    assert result["skipped"] == ["Widget"]


def test_load_type_schema_warns_on_legacy_shape(tmp_pack_env, caplog):
    types_dir = tmp_pack_env
    legacy = {"node_type": "Widget", "pack": "testpack", "required": [], "optional": ["name"]}
    (types_dir / "Widget.yaml").write_text(yaml.safe_dump(legacy), encoding="utf-8")

    schema_loader.load_type_schema.cache_clear()
    with caplog.at_level("WARNING"):
        schema_loader.load_type_schema("Widget")
    assert any("legacy shape" in rec.message for rec in caplog.records)


def test_installed_pack_stub_files_have_current_shape():
    """Live-directory regression check for issue #38.

    schema_pack_install artifacts (schemas/types/*.yaml with a `pack:`
    field) are gitignored, so a fresh checkout/CI runner normally has none
    of them -- only the hand-written core types. In that case there is
    nothing to check, and this must SKIP rather than pass, because a silent
    pass here is indistinguishable from "verified clean" -- which is
    exactly the kind of false confidence that let the original stale-stub
    bug go unnoticed. The tmp_path-fixture tests above
    (test_install_pack_migrates_legacy_shape_stub etc.) are what actually
    exercise the detection/migration logic in CI; this test only adds value
    in an environment (e.g. a real local install) that has pack-generated
    files on disk.
    """
    generated = [
        (path, data)
        for path in sorted(schema_loader.SCHEMAS_DIR.glob("*.yaml"))
        if isinstance((data := yaml.safe_load(path.read_text(encoding="utf-8"))), dict)
        and data.get("pack")
    ]
    if not generated:
        pytest.skip(
            "no pack-generated schema stubs present in this checkout "
            "(schema_pack_install output is gitignored) -- nothing to scan here"
        )

    stale = [path.name for path, data in generated if "properties" not in data]
    assert stale == [], f"legacy-shape schema stub(s) found, run install_pack to migrate: {stale}"


def _install_overlap_pack(tmp_path, monkeypatch, existing_widget_file=None):
    """Set up a pack whose manifest declares the same field in both
    `required` and `optional` (issue #107), optionally with a pre-existing
    legacy-shape Widget.yaml to route install_pack through the migration
    branch instead of the fresh-create branch.
    """
    packs_dir = tmp_path / "packs"
    types_dir = tmp_path / "types"
    packs_dir.mkdir()
    types_dir.mkdir()

    manifest = {
        "name": "overlappack",
        "version": "1.0.0",
        "types": ["Widget"],
        "spaces": ["concept"],
        "type_specs": {
            "Widget": {
                "space": "concept",
                "required": ["name"],
                "optional": ["name", "description"],  # #107: same field, both lists
            }
        },
    }
    (packs_dir / "overlappack.yaml").write_text(yaml.safe_dump(manifest), encoding="utf-8")
    monkeypatch.setattr(pack_registry, "_PACKS_DIR", packs_dir)
    monkeypatch.setattr(pack_registry, "_TYPES_DIR", types_dir)
    monkeypatch.setattr(schema_loader, "SCHEMAS_DIR", types_dir)
    schema_loader.load_type_schema.cache_clear()

    if existing_widget_file is not None:
        (types_dir / "Widget.yaml").write_text(existing_widget_file, encoding="utf-8")

    return types_dir


def test_install_pack_required_wins_over_manifest_optional_overlap(tmp_path, monkeypatch):
    """Issue #107: manifest `type_specs.Widget` lists `name` in BOTH
    `required` and `optional`. `_build_type_schema`'s optional-fields loop
    used to overwrite whatever the required-fields loop wrote, with no
    existence check -- unlike the `extra_required`/`extra_optional` handling
    a few lines down in the same function, which already guards with
    `if field_name in/not in properties`. required must win here too.
    """
    types_dir = _install_overlap_pack(tmp_path, monkeypatch)
    result = pack_registry.install_pack("overlappack")
    assert result["created"] == ["Widget"]

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data["properties"]["name"]["required"] is True
    assert data["properties"]["description"]["required"] is False

    schema_loader.load_type_schema.cache_clear()
    missing = validate_node_properties("Widget", {"description": "x"})
    assert missing.valid is False
    assert "name" in missing.error


def test_install_pack_warns_on_manifest_required_optional_overlap(tmp_path, monkeypatch, caplog):
    """Issue #107 asks that the contradiction itself be surfaced, not just
    silently resolved in required's favour -- a pack author who lists the
    same field twice made a mistake and should be told.
    """
    _install_overlap_pack(tmp_path, monkeypatch)
    with caplog.at_level("WARNING"):
        pack_registry.install_pack("overlappack")
    assert any(
        "name" in rec.message and "required" in rec.message and "optional" in rec.message
        for rec in caplog.records
    )


def test_install_pack_migration_report_does_not_contradict_itself_on_overlap(tmp_path, monkeypatch, caplog):
    """Issue #107 (codex design-review round 1 counterexample): the
    migration branch computes `revived_required`/`revived_optional`
    independently from the manifest's `required`/`optional` lists. When
    those two manifest lists themselves overlap on a field missing from the
    old on-disk file, both `revived_required` and `revived_optional` used
    to include that field -- `revived_manifest_fields` then reported `name`
    as simultaneously revived-required and revived-optional, contradicting
    itself (the same class of contradiction PR #104's review already closed
    between `preserved_extra_fields` and `revived_manifest_fields`).
    """
    legacy = {
        "node_type": "Widget",
        "pack": "overlappack",
        "required": [],
        "optional": ["description"],  # old file never had `name` at all
    }
    existing = "# Auto-generated by schema pack 'overlappack' v1.0.0\n" + yaml.safe_dump(legacy)
    types_dir = _install_overlap_pack(tmp_path, monkeypatch, existing_widget_file=existing)

    with caplog.at_level("WARNING"):
        result = pack_registry.install_pack("overlappack")
    assert result["migrated"] == ["Widget"]

    revived = result["revived_manifest_fields"]["Widget"]
    assert "name" in revived["required"]
    assert "name" not in revived["optional"]  # must not claim `name` both ways

    data = yaml.safe_load((types_dir / "Widget.yaml").read_text(encoding="utf-8"))
    assert data["properties"]["name"]["required"] is True


def test_install_pack_warns_on_overlap_even_when_existing_schema_is_current_shape(
    tmp_path, monkeypatch, caplog
):
    """Issue #107 (review round 9): when a type's on-disk schema is already
    current-shape (has `properties`), install_pack skips it without ever
    calling `_build_type_schema` -- so reinstalling a pack whose manifest
    now contradicts itself (same field in both `required` and `optional`)
    used to stay completely silent. The file is correctly left untouched
    either way; only the warning was missing.
    """
    current_shape = (
        "# Auto-generated by schema pack 'overlappack' v1.0.0\n"
        + yaml.safe_dump(
            {
                "node_type": "Widget",
                "pack": "overlappack",
                "properties": {
                    "name": {"type": "string", "required": True},
                    "description": {"type": "string", "required": False},
                },
            }
        )
    )
    types_dir = _install_overlap_pack(tmp_path, monkeypatch, existing_widget_file=current_shape)
    before = (types_dir / "Widget.yaml").read_text(encoding="utf-8")

    with caplog.at_level("WARNING"):
        result = pack_registry.install_pack("overlappack")
    assert result["skipped"] == ["Widget"]

    after = (types_dir / "Widget.yaml").read_text(encoding="utf-8")
    assert after == before  # skip means skip -- no rewrite, current-shape or not

    # #107 (review round 10): this skip path never rewrites the file, so
    # "required wins" is a false claim here -- the field keeps whatever
    # required value the existing file already has. The warning must say
    # so, not the regenerated-path wording that implies enforcement changed.
    matching = [
        rec.message
        for rec in caplog.records
        if "name" in rec.message and "required" in rec.message and "optional" in rec.message
    ]
    assert matching, "expected an overlap warning"
    assert not any("optional -- required wins" in msg for msg in matching), (
        f"skip-path warning must not unconditionally claim required wins "
        f"(file is unchanged): {matching}"
    )
    assert any("unchanged" in msg and "regenerat" in msg for msg in matching), (
        f"skip-path warning should say the existing file is left unchanged "
        f"and required only wins once the schema is regenerated: {matching}"
    )


# --------------------------------------------------------------------------
# Issue #108: install_pack's created/migrated/skipped (and uninstall_pack's
# removed/kept_user_customised) must be mutually exclusive. A manifest that
# lists the same type name more than once used to make the per-type loop
# visit that type twice, and the second visit always saw a different
# on-disk state than the first (the first visit had just written or removed
# the file) -- so the same type name landed in two buckets at once, and
# total_types counted the raw manifest length instead of the number of
# distinct types actually processed.
# --------------------------------------------------------------------------


def _write_duplicate_types_pack(tmp_path, monkeypatch, *, types, name="duppack", existing_files=None):
    """Set up a pack manifest whose `types` list may repeat a name, and
    optionally pre-seed on-disk type files so a repeated name's first and
    second visit land in different branches (install_pack's create/skip or
    migrate/skip, uninstall_pack's remove/keep).
    """
    packs_dir = tmp_path / "packs"
    types_dir = tmp_path / "types"
    packs_dir.mkdir()
    types_dir.mkdir()

    manifest = {
        "name": name,
        "version": "1.0.0",
        "types": types,
        "spaces": ["concept"],
    }
    (packs_dir / f"{name}.yaml").write_text(yaml.safe_dump(manifest), encoding="utf-8")
    monkeypatch.setattr(pack_registry, "_PACKS_DIR", packs_dir)
    monkeypatch.setattr(pack_registry, "_TYPES_DIR", types_dir)
    monkeypatch.setattr(schema_loader, "SCHEMAS_DIR", types_dir)
    schema_loader.load_type_schema.cache_clear()

    for fname, content in (existing_files or {}).items():
        (types_dir / fname).write_text(content, encoding="utf-8")

    return types_dir


def test_install_pack_total_types_matches_created_migrated_skipped_without_duplicates(tmp_pack_env):
    """#108 baseline: with no duplicate type names the three buckets are
    already mutually exclusive and total_types already equals their sum --
    this must keep holding after the #108 fix, not just the duplicate case.
    """
    types_dir = tmp_pack_env
    result = pack_registry.install_pack("testpack")
    assert result["created"] == ["Widget"]
    assert result["total_types"] == 1
    assert len(result["created"]) + len(result["migrated"]) + len(result["skipped"]) == result["total_types"]
    assert types_dir  # fixture yields the types dir; keep it referenced


def test_install_pack_duplicate_type_name_migrated_and_skipped_do_not_overlap(tmp_path, monkeypatch, caplog):
    """#108: manifest lists `Widget` twice. A pre-existing legacy-shape stub
    routes the FIRST occurrence through the migrate branch; before the #108
    fix the loop then revisited `Widget` a second time and, since the file
    it had just written is now current-shape, the SECOND occurrence fell
    into the skip branch -- `migrated` and `skipped` both named `Widget`,
    and `total_types` counted 2 for a manifest that names one distinct type.
    """
    legacy = {
        "node_type": "Widget",
        "pack": "duppack",
        "required": ["name"],
        "optional": ["description"],
    }
    existing = "# Auto-generated by schema pack 'duppack' v1.0.0\n" + yaml.safe_dump(legacy)
    _write_duplicate_types_pack(
        tmp_path, monkeypatch, types=["Widget", "Widget"], existing_files={"Widget.yaml": existing}
    )

    with caplog.at_level("WARNING"):
        result = pack_registry.install_pack("duppack")

    assert result["migrated"] == ["Widget"]
    assert result["skipped"] == []
    assert set(result["migrated"]) & set(result["skipped"]) == set()
    assert result["total_types"] == 1
    assert len(result["created"]) + len(result["migrated"]) + len(result["skipped"]) == result["total_types"]
    assert any("duplicate" in rec.message and "Widget" in rec.message for rec in caplog.records)


def test_install_pack_duplicate_type_name_created_and_skipped_do_not_overlap(tmp_path, monkeypatch):
    """#108, created/skipped variant: with no pre-existing file, the FIRST
    `Widget` occurrence creates schemas/types/Widget.yaml; before the fix
    the loop's SECOND `Widget` occurrence then found that just-created
    current-shape file and fell into skip -- `created` and `skipped` both
    named `Widget`.
    """
    types_dir = _write_duplicate_types_pack(tmp_path, monkeypatch, types=["Widget", "Widget"])

    result = pack_registry.install_pack("duppack")

    assert result["created"] == ["Widget"]
    assert result["skipped"] == []
    assert result["total_types"] == 1
    assert len(result["created"]) + len(result["migrated"]) + len(result["skipped"]) == result["total_types"]
    assert (types_dir / "Widget.yaml").exists()


def test_install_pack_warns_once_regardless_of_duplicate_count(tmp_path, monkeypatch, caplog):
    """#108: three occurrences of the same name must still produce exactly
    one duplicate-type warning, not one per repeat -- `_warn_on_duplicate_types`
    runs once per install_pack call, before the per-type loop starts.
    """
    _write_duplicate_types_pack(tmp_path, monkeypatch, types=["Widget", "Widget", "Widget"])

    with caplog.at_level("WARNING"):
        result = pack_registry.install_pack("duppack")

    assert result["created"] == ["Widget"]
    assert result["total_types"] == 1
    duplicate_warnings = [
        rec.message for rec in caplog.records if "duplicate" in rec.message and "Widget" in rec.message
    ]
    assert len(duplicate_warnings) == 1, duplicate_warnings


def test_install_pack_dedups_while_preserving_first_occurrence_order(tmp_path, monkeypatch):
    """#108: dedup must keep first-occurrence order, not just uniqueness --
    a manifest naming `Widget`, `Gadget`, `Widget` processes `Gadget`
    exactly once, in its original position, alongside `Widget`.
    """
    types_dir = _write_duplicate_types_pack(tmp_path, monkeypatch, types=["Widget", "Gadget", "Widget"])

    result = pack_registry.install_pack("duppack")

    assert result["created"] == ["Widget", "Gadget"]
    assert result["total_types"] == 2
    assert (types_dir / "Widget.yaml").exists()
    assert (types_dir / "Gadget.yaml").exists()


def test_install_pack_unhashable_type_entry_is_rejected_not_crashed(tmp_path, monkeypatch):
    """#108 regression guard: `_dedup_types` uses `dict.fromkeys`, which
    raises TypeError on an unhashable entry. That entry must never reach
    it -- `safe_schema_name`'s leading `isinstance(name, str)` check makes
    `_unsafe_names` reject a non-str entry (a manifest author's typo'd
    mapping, say) before dedup ever runs, so install_pack returns a
    structured error instead of crashing, and writes nothing.
    """
    types_dir = _write_duplicate_types_pack(tmp_path, monkeypatch, types=["Widget", {"bad": "value"}])

    result = pack_registry.install_pack("duppack")

    assert "error" in result, result
    assert not (types_dir / "Widget.yaml").exists()
    assert list(types_dir.iterdir()) == []


def test_install_pack_rejects_duplicated_unsafe_name_without_deduping_the_report(tmp_path, monkeypatch):
    """#108 x #109: two occurrences of the SAME unsafe name must both be
    named in the refusal -- `_unsafe_names` runs before any dedup step, so
    it must never silently collapse `['../evil', '../evil']` down to one
    entry and understate how many manifest lines are actually broken.
    """
    types_dir = _write_duplicate_types_pack(tmp_path, monkeypatch, types=["../evil", "../evil"])

    result = pack_registry.install_pack("duppack")

    assert "error" in result, result
    assert result["error"].count("../evil") == 2
    assert list(types_dir.iterdir()) == []


def test_uninstall_pack_duplicate_type_name_does_not_double_count_kept(tmp_path, monkeypatch, caplog):
    """#108 sibling path: manifest lists `Widget` twice. The file is
    user-customised (no generation marker), so it is kept, not removed --
    but before the #108 fix the loop visited `Widget` twice and appended it
    to `kept_user_customised` BOTH times, so a list meant to name each
    surviving type once named the same file twice.
    """
    custom = "custom: true\n"
    types_dir = _write_duplicate_types_pack(
        tmp_path, monkeypatch, types=["Widget", "Widget"], existing_files={"Widget.yaml": custom}
    )

    with caplog.at_level("WARNING"):
        result = pack_registry.uninstall_pack("duppack")

    assert result["kept_user_customised"] == ["Widget"]
    assert result["removed"] == []
    assert (types_dir / "Widget.yaml").exists()
    duplicate_warnings = [
        rec.message for rec in caplog.records if "duplicate" in rec.message and "Widget" in rec.message
    ]
    assert duplicate_warnings
    # The warning is shared with install_pack's call site: it must not claim
    # a type was "installed" when this call removed (or, here, kept) it.
    assert not any("installed" in msg for msg in duplicate_warnings), duplicate_warnings


def test_uninstall_pack_force_with_duplicate_type_name_removes_once(tmp_path, monkeypatch, caplog):
    """#108 x force=True: a manifest naming `Widget` twice must remove the
    file once and report it once even under a forced removal -- dedup runs
    ahead of the removal loop regardless of `force`.
    """
    generated = "pack: duppack\nnode_type: Widget\n"
    types_dir = _write_duplicate_types_pack(
        tmp_path, monkeypatch, types=["Widget", "Widget"], existing_files={"Widget.yaml": generated}
    )

    with caplog.at_level("WARNING"):
        result = pack_registry.uninstall_pack("duppack", force=True)

    assert result["removed"] == ["Widget"]
    assert result["kept_user_customised"] == []
    assert not (types_dir / "Widget.yaml").exists()
    duplicate_warnings = [
        rec.message for rec in caplog.records if "duplicate" in rec.message and "Widget" in rec.message
    ]
    assert len(duplicate_warnings) == 1, duplicate_warnings
    assert not any("installed" in msg for msg in duplicate_warnings), duplicate_warnings


def test_uninstall_pack_removed_and_kept_sum_to_deduped_type_count(tmp_path, monkeypatch):
    """#108 invariant, uninstall side, mixed removed+kept: `Widget` is
    generated (removed) and `Gadget` is user-customised (kept), with
    `Gadget` -- the type that survives -- repeated in the manifest.

    The duplicate must land on the KEPT type, not the removed one: once a
    type is removed its file no longer exists, so a second visit hits the
    loop's `if not path.exists(): continue` guard and is a no-op with or
    without dedup. A duplicated kept type has no such guard -- pre-fix,
    each visit re-evaluates the still-present file and appends it to
    `kept_user_customised` again, so only this arrangement actually
    discriminates the fix.
    """
    generated = "pack: duppack\nnode_type: Widget\n"
    custom = "custom: true\n"
    types_dir = _write_duplicate_types_pack(
        tmp_path,
        monkeypatch,
        types=["Widget", "Gadget", "Gadget"],
        existing_files={"Widget.yaml": generated, "Gadget.yaml": custom},
    )

    result = pack_registry.uninstall_pack("duppack")

    assert result["removed"] == ["Widget"]
    assert result["kept_user_customised"] == ["Gadget"]
    assert len(result["removed"]) + len(result["kept_user_customised"]) == 2
    assert not (types_dir / "Widget.yaml").exists()
    assert (types_dir / "Gadget.yaml").exists()
