"""Shared validation skeleton for codex_workers adapters.

The three worker adapters (landscape, github_trending, soeak) historically
copy-pasted the same ``validate*_bundle`` shape: iterate required fields and
count passes, compute completeness, score the bundle semantically, derive an
autoresearch verdict, then decide ``status``/``next_action``. ``run_validation``
extracts that skeleton; the per-worker differences are injected as callbacks and
flags so each worker keeps its exact original behaviour.
"""

from __future__ import annotations

from typing import Callable

from crabharness.models import ArtifactBundle, MissionSpec, ValidationIssue, ValidationReport
from crabharness.semantic import determine_autoresearch_verdict, score_bundle_semantically

# Returns ``True`` when ``field`` is satisfied by the bundle. Workers that need
# to emit a custom missing-field message receive the field name and return a
# bool; the standard ``missing_<field>`` error is generated by the skeleton.
FieldCheck = Callable[[ArtifactBundle, str], bool]

# Appends any worker-specific issues (e.g. category coverage warnings, missing
# db / fatal progress errors) after the required-field loop. Mutates ``issues``.
ExtraChecks = Callable[[ArtifactBundle, list[ValidationIssue]], None]

# Returns the final semantic score given the heuristic score and the bundle.
# Defaults to the heuristic score unchanged; landscape overrides it to take the
# max with its domain-specific score.
SemanticOverride = Callable[[float, ArtifactBundle], float]

# Returns ``True`` when the run should be hard-failed (status=fail / reject).
# github_trending & soeak fail when ``passed == 0 and issues``; landscape fails
# when both documents and use_cases are empty.
FailCheck = Callable[[ArtifactBundle, int, list[ValidationIssue]], bool]


def run_validation(
    bundle: ArtifactBundle,
    mission: MissionSpec,
    *,
    field_check: FieldCheck,
    missing_message: Callable[[str], str],
    default_required_fields: list[str] | None = None,
    extra_checks: ExtraChecks | None = None,
    semantic_override: SemanticOverride | None = None,
    apply_semantic_gate: bool = False,
    fail_check: FailCheck,
) -> ValidationReport:
    issues: list[ValidationIssue] = []

    required = mission.success_criteria.required_fields
    if default_required_fields is not None:
        required = required or default_required_fields

    checks_total = max(len(required), 1)
    passed = 0
    for field in required:
        if field_check(bundle, field):
            passed += 1
        else:
            issues.append(
                ValidationIssue(
                    code=f"missing_{field}",
                    severity="error",
                    message=missing_message(field),
                )
            )

    if extra_checks is not None:
        extra_checks(bundle, issues)

    completeness = round(passed / checks_total, 3)

    semantic_result = score_bundle_semantically(bundle, mission)
    semantic_score = semantic_result.get("semantic_score", 0.0)
    if semantic_override is not None:
        semantic_score = semantic_override(semantic_score, bundle)

    verdict = determine_autoresearch_verdict(
        completeness_score=completeness,
        semantic_score=semantic_score,
        mission=mission,
    )

    threshold = mission.success_criteria.completeness_threshold
    has_error = any(issue.severity == "error" for issue in issues)
    passes_threshold = completeness >= threshold and not has_error
    if apply_semantic_gate:
        semantic_threshold = mission.success_criteria.min_semantic_score or 0.0
        passes_threshold = passes_threshold and semantic_score >= semantic_threshold

    status = "pass" if passes_threshold else "retry"
    next_action = "promote" if status == "pass" else "retry"

    if fail_check(bundle, passed, issues):
        status = "fail"
        next_action = "reject"

    return ValidationReport(
        run_id=bundle.run_id,
        mission_id=mission.mission_id,
        status=status,
        completeness_score=completeness,
        semantic_score=semantic_score,
        semantic_verdict=verdict,
        issues=issues,
        next_action=next_action,
    )
